#!/usr/bin/perl
# -*- coding: utf-8; -*-
# vim: fenc=utf-8

use utf8;

$self->{more_texts} = {
  'Add Machine'                 => 'Maschine erfassen',
  'Add Service Contract'        => 'Wartungsvertrag erfassen',
  'Admin'                       => 'Administration',
  'Appointment Category'        => 'Termin Kategorie',
  'Appointments'                => 'Termine',
  'CRM admin'                   => '',
  'CRM create customers, vendors and contacts' => '',
  'CRM follow up'               => '',
  'CRM know how'                => '',
  'CRM notices'                 => '',
  'CRM opportunity'             => '',
  'CRM optional software'       => '',
  'CRM other'                   => '',
  'CRM search'                  => '',
  'CRM send email'              => '',
  'CRM services'                => '',
  'CRM status'                  => '',
  'CRM termin'                  => '',
  'CRM user'                    => '',
  'CRM'                         => 'CRM',
  'Catalog'                     => 'Katalog',
  'DHL'                         => 'DHL',
  'Document Template'           => 'Dokumentvorlage',
  'Documents'                   => 'Dokumente',
  'Etikett'                     => 'Etikett',
  'EuR'                         => 'EuR',
  'Knowledge'                   => 'Wissen',
  'Label'                       => 'Etikett',
  'Machine'                     => 'Maschine',
  'Message'                     => 'Nachricht',
  'Opportunity'                 => 'Auftragschance',
  'Other'                       => 'Sonstiges',
  'Packliste'                   => 'Packliste',
  'Partsedit'                   => 'Wareneditor',
  'Person'                      => 'Person',
  'Service Contract'            => 'Wartungsvertrag',
  'Time Tracking'               => 'Zeiterfassung',
  'User Groups'                 => 'Gruppen',
  'Warehouse correction'        => 'Lagerkorrektur',
  'Warehouse list'              => 'Inventurliste',
  'ZM'                          => 'ZM',
  'eBayImporter'                => 'eBay-Importierer',
};

1;
