-- @tag: release_2_4_1
-- @description: Leeres Script, das von allen bis zum Release 2.4.1 hinzugef&uuml;gten Upgradescripten abh&auml;ngt, um ein fest definiertes Schema f&uuml;r 2.4.1 zu definieren.
-- @depends: chart_names rename_buchungsgruppen_accounts_16_19_percent language_output_formatting units_translations_and_singular_plural_distinction invalid_taxkesy customer_vendor_ustid_length
