-- @tag: schema_normalization_2
-- @description: Datenbankschema Normalisierungen Teil 2
-- @depends: schema_normalization_1

ALTER TABLE acc_trans ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE audittrail ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE customertax ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE datev ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE defaults ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE department ADD PRIMARY KEY (id);
ALTER TABLE dpt_trans ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE exchangerate ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE finanzamt ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE follow_up_access ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE gifi ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE inventory ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE licenseinvoice ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE partsgroup ADD PRIMARY KEY (id);
ALTER TABLE partstax ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE prices ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE record_links ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE rmaitems ADD PRIMARY KEY (id);
ALTER TABLE status ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE tax_zones ADD PRIMARY KEY (id);
ALTER TABLE todo_user_config ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE translation ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE units_language ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE vendortax ADD COLUMN id SERIAL PRIMARY KEY;
