#!/bin/sh

# Erstellt die benotigten Symlinks

ln -vsf login.pl admin.pl
for i in ap ar bp ca cp ct gl ic ir is menu oe pe rc rp datev licenses fa ustva; do
  ln -vsf am.pl $i.pl
done

cd bin/lynx
for i in admin  am  ap  ar  arap  bp  ca  cp  ct  gl  ic  io  ir  is  login  oe  pe  rc  rp datev  licenses fa ustva; do
  ln -vsf ../mozilla/$i.pl $i.pl
done
