package SL::Helper::ISO3166;

use strict;
use warnings;
use utf8;

use Exporter qw(import);
our @EXPORT_OK = qw(map_name_to_alpha_2_code get_alpha_2_mappings);

use List::Util qw(first);

my @alpha_2_mappings = (
  [ 'AD', qr{^(?:AD|Andorra)$}i, 'Andorra', 'Andorra'],
  [ 'AE', qr{^(?:AE|United Arab Emirates|Vereinigte Arabische Emirate)$}i, 'United Arab Emirates', 'Vereinigte Arabische Emirate'],
  [ 'AF', qr{^(?:AF|Afghanistan)$}i, 'Afghanistan', 'Afghanistan'],
  [ 'AG', qr{^(?:AG|Antigua and Barbuda|Antigua und Barbuda)$}i, 'Antigua and Barbuda', 'Antigua und Barbuda'],
  [ 'AI', qr{^(?:AI|Anguilla)$}i, 'Anguilla', 'Anguilla'],
  [ 'AL', qr{^(?:AL|Albania|Albanien)$}i, 'Albania', 'Albanien'],
  [ 'AM', qr{^(?:AM|Armenia|Armenien)$}i, 'Armenia', 'Armenien'],
  [ 'AO', qr{^(?:AO|Angola)$}i, 'Angola', 'Angola'],
  [ 'AQ', qr{^(?:AQ|Antarctica|Antarktis)$}i, 'Antarctica', 'Antarktis'],
  [ 'AR', qr{^(?:AR|Argentina|Argentinien)$}i, 'Argentina', 'Argentinien'],
  [ 'AS', qr{^(?:AS|American Samoa|Amerikanisch-Samoa)$}i, 'American Samoa', 'Amerikanisch-Samoa'],
  [ 'AT', qr{^(?:AT|A|Austria|Österreich)$}i, 'Austria', 'Österreich'],
  [ 'AU', qr{^(?:AU|Australia|Australien)$}i, 'Australia', 'Australien'],
  [ 'AW', qr{^(?:AW|Aruba)$}i, 'Aruba', 'Aruba'],
  [ 'AX', qr{^(?:AX|Åland Islands|Åland)$}i, 'Åland Islands', 'Åland'],
  [ 'AZ', qr{^(?:AZ|Azerbaijan|Aserbaidschan)$}i, 'Azerbaijan', 'Aserbaidschan'],
  [ 'BA', qr{^(?:BA|Bosnia and Herzegovina|Bosnien und Herzegowina)$}i, 'Bosnia and Herzegovina', 'Bosnien und Herzegowina'],
  [ 'BB', qr{^(?:BB|Barbados)$}i, 'Barbados', 'Barbados'],
  [ 'BD', qr{^(?:BD|Bangladesh|Bangladesch)$}i, 'Bangladesh', 'Bangladesch'],
  [ 'BE', qr{^(?:BE|Belgium|Belgien)$}i, 'Belgium', 'Belgien'],
  [ 'BF', qr{^(?:BF|Burkina Faso)$}i, 'Burkina Faso', 'Burkina Faso'],
  [ 'BG', qr{^(?:BG|Bulgaria|Bulgarien)$}i, 'Bulgaria', 'Bulgarien'],
  [ 'BH', qr{^(?:BH|Bahrain)$}i, 'Bahrain', 'Bahrain'],
  [ 'BI', qr{^(?:BI|Burundi)$}i, 'Burundi', 'Burundi'],
  [ 'BJ', qr{^(?:BJ|Benin)$}i, 'Benin', 'Benin'],
  [ 'BL', qr{^(?:BL|Saint Barthélemy|Saint-Barthélemy)$}i, 'Saint Barthélemy', 'Saint-Barthélemy'],
  [ 'BM', qr{^(?:BM|Bermuda)$}i, 'Bermuda', 'Bermuda'],
  [ 'BN', qr{^(?:BN|Brunei Darussalam|Brunei)$}i, 'Brunei Darussalam', 'Brunei'],
  [ 'BO', qr{^(?:BO|Bolivia \(Plurinational State of\)|Bolivien)$}i, 'Bolivia', 'Bolivien'],
  [ 'BQ', qr{^(?:BQ|Bonaire, Sint Eustatius and Saba)$}i, 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius und Saba'],
  [ 'BR', qr{^(?:BR|Brazil|Brasilien)$}i, 'Brazil', 'Brasilien'],
  [ 'BS', qr{^(?:BS|Bahamas)$}i, 'Bahamas', 'Bahamas'],
  [ 'BT', qr{^(?:BT|Bhutan)$}i, 'Bhutan', 'Bhutan'],
  [ 'BV', qr{^(?:BV|Bouvet Island|Bouvetinsel)$}i, 'Bouvet Island', 'Bouvetinsel'],
  [ 'BW', qr{^(?:BW|Botswana)$}i, 'Botswana', 'Botswana'],
  [ 'BY', qr{^(?:BY|Belarus)$}i, 'Belarus', 'Belarus'],
  [ 'BZ', qr{^(?:BZ|Belize)$}i, 'Belize', 'Belize'],
  [ 'CA', qr{^(?:CA|Canada|Kanada)$}i, 'Canada', 'Kanada'],
  [ 'CC', qr{^(?:CC|Cocos \(Keeling\) Islands|Cocos Islands|Keeling Islands|Kokosinseln)$}i, 'Cocos (Keeling) Islands', 'Kokosinseln'],
  [ 'CD', qr{^(?:CD|Congo, Democratic Republic of the|Demokratische Republik Kongo)$}i, 'Congo, Democratic Republic of the', 'Demokratische Republik Kongo'],
  [ 'CF', qr{^(?:CF|Central African Republic|Zentralafrikanische Republik)$}i, 'Central African Republic', 'Zentralafrikanische Republik'],
  [ 'CG', qr{^(?:CG|Congo|Republik Kongo)$}i, 'Congo', 'Republik Kongo'],
  [ 'CH', qr{^(?:CH|Switzerland|Schweiz)$}i, 'Switzerland', 'Schweiz'],
  [ 'CI', qr{^(?:CI|Côte d'Ivoire|Elfenbeinküste)$}i, 'Côte d\'Ivoire', 'Elfenbeinküste'],
  [ 'CK', qr{^(?:CK|Cook Islands|Cookinseln)$}i, 'Cook Islands', 'Cookinseln'],
  [ 'CL', qr{^(?:CL|Chile)$}i, 'Chile', 'Chile'],
  [ 'CM', qr{^(?:CM|Cameroon|Kamerun)$}i, 'Cameroon', 'Kamerun'],
  [ 'CN', qr{^(?:CN|China|P\.?\s?R\.?\s?(of )?C\.?(hina)?|Volksrepublik China)$}i, 'China', 'Volksrepublik China'],
  [ 'CO', qr{^(?:CO|Colombia|Kolumbien)$}i, 'Colombia', 'Kolumbien'],
  [ 'CR', qr{^(?:CR|Costa Rica)$}i, 'Costa Rica', 'Costa Rica'],
  [ 'CU', qr{^(?:CU|Cuba|Kuba)$}i, 'Cuba', 'Kuba'],
  [ 'CV', qr{^(?:CV|Cabo Verde|Kap Verde)$}i, 'Cabo Verde', 'Kap Verde'],
  [ 'CW', qr{^(?:CW|Curaçao)$}i, 'Curaçao', 'Curaçao'],
  [ 'CX', qr{^(?:CX|Christmas Island|Weihnachtsinsel)$}i, 'Christmas Island', 'Weihnachtsinsel'],
  [ 'CY', qr{^(?:CY|Cyprus|Zypern)$}i, 'Cyprus', 'Zypern'],
  [ 'CZ', qr{^(?:CZ|Czechia|Czech Republic|Tschechien|Tschechische Republik)$}i, 'Czech Republic', 'Tschechien'],
  [ 'DE', qr{^(?:DE|Germany|D|Deutschland)$}i, 'Germany', 'Deutschland'],
  [ 'DJ', qr{^(?:DJ|Djibouti|Dschibuti)$}i, 'Djibouti', 'Dschibuti'],
  [ 'DK', qr{^(?:DK|Denmark|Dänemark)$}i, 'Denmark', 'Dänemark'],
  [ 'DM', qr{^(?:DM|Dominica)$}i, 'Dominica', 'Dominica'],
  [ 'DO', qr{^(?:DO|Dominican Republic|Dominikanische Republik)$}i, 'Dominican Republic', 'Dominikanische Republik'],
  [ 'DZ', qr{^(?:DZ|Algeria|Algerien)$}i, 'Algeria', 'Algerien'],
  [ 'EC', qr{^(?:EC|Ecuador)$}i, 'Ecuador', 'Ecuador'],
  [ 'EE', qr{^(?:EE|Estonia|Estland)$}i, 'Estonia', 'Estland'],
  [ 'EG', qr{^(?:EG|Egypt|Ägypten)$}i, 'Egypt', 'Ägypten'],
  [ 'EH', qr{^(?:EH|Western Sahara|Westsahara)$}i, 'Western Sahara', 'Westsahara'],
  [ 'ER', qr{^(?:ER|Eritrea)$}i, 'Eritrea', 'Eritrea'],
  [ 'ES', qr{^(?:ES|Spain|Spanien)$}i, 'Spain', 'Spanien'],
  [ 'ET', qr{^(?:ET|Ethiopia|Äthiopien)$}i, 'Ethiopia', 'Äthiopien'],
  [ 'FI', qr{^(?:FI|Finland|Finnland)$}i, 'Finland', 'Finnland'],
  [ 'FJ', qr{^(?:FJ|Fiji|Fidschi)$}i, 'Fiji', 'Fidschi'],
  [ 'FK', qr{^(?:FK|Falkland Islands \(Malvinas\)|Falkland Islands|Falklands|Falklandinseln)$}i, 'Falkland Islands (Malvinas)', 'Falklandinseln'],
  [ 'FM', qr{^(?:FM|Micronesia \(Federated States of\)|Micronesia|Föderierte Staaten von Mikronesien)$}i, 'Micronesia, Federated States of', 'Föderierte Staaten von Mikronesien'],
  [ 'FO', qr{^(?:FO|Faroe Islands|Färöer)$}i, 'Faroe Islands', 'Färöer'],
  [ 'FR', qr{^(?:FR|France|Frankreich)$}i, 'France', 'Frankreich'],
  [ 'GA', qr{^(?:GA|Gabon|Gabun)$}i, 'Gabon', 'Gabun'],
  [ 'GB', qr{^(?:GB|United Kingdom( of Great Britain and Northern Ireland)?|Vereinigtes Königreich)$}i, 'United Kingdom', 'Vereinigtes Königreich'],
  [ 'GD', qr{^(?:GD|Grenada)$}i, 'Grenada', 'Grenada'],
  [ 'GE', qr{^(?:GE|Georgia|Georgien)$}i, 'Georgia', 'Georgien'],
  [ 'GF', qr{^(?:GF|French Guiana|Französisch-Guayana)$}i, 'French Guiana', 'Französisch-Guayana'],
  [ 'GG', qr{^(?:GG|Guernsey)$}i, 'Guernsey', 'Guernsey (Kanalinsel)'],
  [ 'GH', qr{^(?:GH|Ghana)$}i, 'Ghana', 'Ghana'],
  [ 'GI', qr{^(?:GI|Gibraltar)$}i, 'Gibraltar', 'Gibraltar'],
  [ 'GL', qr{^(?:GL|Greenland|Grönland)$}i, 'Greenland', 'Grönland'],
  [ 'GM', qr{^(?:GM|Gambia)$}i, 'Gambia', 'Gambia'],
  [ 'GN', qr{^(?:GN|Guinea)$}i, 'Guinea', 'Guinea'],
  [ 'GP', qr{^(?:GP|Guadeloupe)$}i, 'Guadeloupe', 'Guadeloupe'],
  [ 'GQ', qr{^(?:GQ|Equatorial Guinea|Äquatorialguinea)$}i, 'Equatorial Guinea', 'Äquatorialguinea'],
  [ 'GR', qr{^(?:GR|Greece|Griechenland)$}i, 'Greece', 'Griechenland'],
  [ 'GS', qr{^(?:GS|South Georgia and the South Sandwich Islands|Südgeorgien und die Südlichen Sandwichinseln)$}i, 'South Georgia and the South Sandwich Islands', 'Südgeorgien und die Südlichen Sandwichinseln'],
  [ 'GT', qr{^(?:GT|Guatemala)$}i, 'Guatemala', 'Guatemala'],
  [ 'GU', qr{^(?:GU|Guam)$}i, 'Guam', 'Guam'],
  [ 'GW', qr{^(?:GW|Guinea-Bissau)$}i, 'Guinea-Bissau', 'Guinea-Bissau'],
  [ 'GY', qr{^(?:GY|Guyana)$}i, 'Guyana', 'Guyana'],
  [ 'HK', qr{^(?:HK|Hong Kong|Hongkong)$}i, 'Hong Kong', 'Hongkong'],
  [ 'HM', qr{^(?:HM|Heard Island and McDonald Islands|Heard und McDonaldinseln)$}i, 'Heard Island and McDonald Islands', 'Heard und McDonaldinseln'],
  [ 'HN', qr{^(?:HN|Honduras)$}i, 'Honduras', 'Honduras'],
  [ 'HR', qr{^(?:HR|Croatia|Kroatien)$}i, 'Croatia', 'Kroatien'],
  [ 'HT', qr{^(?:HT|Haiti)$}i, 'Haiti', 'Haiti'],
  [ 'HU', qr{^(?:HU|Hungary|Ungarn)$}i, 'Hungary', 'Ungarn'],
  [ 'ID', qr{^(?:ID|Indonesia|Indonesien)$}i, 'Indonesia', 'Indonesien'],
  [ 'IE', qr{^(?:IE|Ireland|Irland)$}i, 'Ireland', 'Irland'],
  [ 'IL', qr{^(?:IL|Israel)$}i, 'Israel', 'Israel'],
  [ 'IM', qr{^(?:IM|Isle of Man)$}i, 'Isle of Man', 'Insel Man'],
  [ 'IN', qr{^(?:IN|India|Indien)$}i, 'India', 'Indien'],
  [ 'IO', qr{^(?:IO|British Indian Ocean Territory|Britisches Territorium im Indischen Ozean)$}i, 'British Indian Ocean Territory', 'Britisches Territorium im Indischen Ozean'],
  [ 'IQ', qr{^(?:IQ|Iraq|Irak)$}i, 'Iraq', 'Irak'],
  [ 'IR', qr{^(?:IR|Iran \(Islamic Republic of\)|Iran)$}i, 'Iran', 'Iran'],
  [ 'IS', qr{^(?:IS|Iceland|Island)$}i, 'Iceland', 'Island'],
  [ 'IT', qr{^(?:IT|Italy|Italien)$}i, 'Italy', 'Italien'],
  [ 'JE', qr{^(?:JE|Jersey)$}i, 'Jersey', 'Jersey (Kanalinsel)'],
  [ 'JM', qr{^(?:JM|Jamaica|Jamaika)$}i, 'Jamaica', 'Jamaika'],
  [ 'JO', qr{^(?:JO|Jordan|Jordanien)$}i, 'Jordan', 'Jordanien'],
  [ 'JP', qr{^(?:JP|Japan)$}i, 'Japan', 'Japan'],
  [ 'KE', qr{^(?:KE|Kenya|Kenia)$}i, 'Kenya', 'Kenia'],
  [ 'KG', qr{^(?:KG|Kyrgyzstan|Kirgisistan)$}i, 'Kyrgyzstan', 'Kirgisistan'],
  [ 'KH', qr{^(?:KH|Cambodia|Kambodscha)$}i, 'Cambodia', 'Kambodscha'],
  [ 'KI', qr{^(?:KI|Kiribati)$}i, 'Kiribati', 'Kiribati'],
  [ 'KM', qr{^(?:KM|Comoros|Komoren)$}i, 'Comoros', 'Komoren'],
  [ 'KN', qr{^(?:KN|Saint Kitts and Nevis|St\. Kitts und Nevis)$}i, 'Saint Kitts and Nevis', 'St. Kitts und Nevis'],
  [ 'KP', qr{^(?:KP|Korea \(Democratic People's Republic of\)|Nordkorea)$}i, 'Korea, Democratic People\'s Republic of', 'Nordkorea'],
  [ 'KR', qr{^(?:KR|Korea, Republic of|Republic of Korea|Korea|Südkorea)$}i, 'Korea, Republic of', 'Südkorea'],
  [ 'KW', qr{^(?:KW|Kuwait)$}i, 'Kuwait', 'Kuwait'],
  [ 'KY', qr{^(?:KY|Cayman Islands)$}i, 'Cayman Islands', 'Kaimaninseln'],
  [ 'KZ', qr{^(?:KZ|Kazakhstan|Kasachstan)$}i, 'Kazakhstan', 'Kasachstan'],
  [ 'LA', qr{^(?:LA|Lao People's Democratic Republic|Laos)$}i, 'Lao People\'s Democratic Republic', 'Laos, Demokratische Volksrepublik'],
  [ 'LB', qr{^(?:LB|Lebanon|Libanon)$}i, 'Lebanon', 'Libanon'],
  [ 'LC', qr{^(?:LC|Saint Lucia|St\. Lucia)$}i, 'Saint Lucia', 'St. Lucia'],
  [ 'LI', qr{^(?:LI|Liechtenstein)$}i, 'Liechtenstein', 'Liechtenstein'],
  [ 'LK', qr{^(?:LK|Sri Lanka)$}i, 'Sri Lanka', 'Sri Lanka'],
  [ 'LR', qr{^(?:LR|Liberia)$}i, 'Liberia', 'Liberia'],
  [ 'LS', qr{^(?:LS|Lesotho)$}i, 'Lesotho', 'Lesotho'],
  [ 'LT', qr{^(?:LT|Lithuania|Litauen)$}i, 'Lithuania', 'Litauen'],
  [ 'LU', qr{^(?:LU|Luxembourg|Luxemburg)$}i, 'Luxembourg', 'Luxemburg'],
  [ 'LV', qr{^(?:LV|Latvia|Lettland)$}i, 'Latvia', 'Lettland'],
  [ 'LY', qr{^(?:LY|Libya|Libyen)$}i, 'Libya', 'Libyen'],
  [ 'MA', qr{^(?:MA|Morocco|Marokko)$}i, 'Morocco', 'Marokko'],
  [ 'MC', qr{^(?:MC|Monaco)$}i, 'Monaco', 'Monaco'],
  [ 'MD', qr{^(?:MD|Moldova, Republic of|Moldau)$}i, 'Moldova, Republic of', 'Moldawien (Republik Moldau)'],
  [ 'ME', qr{^(?:ME|Montenegro)$}i, 'Montenegro', 'Montenegro'],
  [ 'MF', qr{^(?:MF|Saint Martin \(French part\)|Saint Martin)$}i, 'Saint Martin', 'Saint Martin'],
  [ 'MG', qr{^(?:MG|Madagascar|Madagaskar)$}i, 'Madagascar', 'Madagaskar'],
  [ 'MH', qr{^(?:MH|Marshall Islands|Marshallinseln)$}i, 'Marshall Islands', 'Marshallinseln'],
  [ 'MK', qr{^(?:MK|North Macedonia|Nordmazedonien)$}i, 'North Macedonia', 'Nordmazedonien'],
  [ 'ML', qr{^(?:ML|Mali)$}i, 'Mali', 'Mali'],
  [ 'MM', qr{^(?:MM|Myanmar)$}i, 'Myanmar', 'Myanmar (Burma)'],
  [ 'MN', qr{^(?:MN|Mongolia|Mongolei)$}i, 'Mongolia', 'Mongolei'],
  [ 'MO', qr{^(?:MO|Macao|Macau)$}i, 'Macao', 'Macau'],
  [ 'MP', qr{^(?:MP|Northern Mariana Islands|Nördliche Marianen)$}i, 'Northern Mariana Islands', 'Nördliche Marianen'],
  [ 'MQ', qr{^(?:MQ|Martinique)$}i, 'Martinique', 'Martinique'],
  [ 'MR', qr{^(?:MR|Mauritania|Mauretanien)$}i, 'Mauritania', 'Mauretanien'],
  [ 'MS', qr{^(?:MS|Montserrat)$}i, 'Montserrat', 'Montserrat'],
  [ 'MT', qr{^(?:MT|Malta)$}i, 'Malta', 'Malta'],
  [ 'MU', qr{^(?:MU|Mauritius)$}i, 'Mauritius', 'Mauritius'],
  [ 'MV', qr{^(?:MV|Maldives|Malediven)$}i, 'Maldives', 'Malediven'],
  [ 'MW', qr{^(?:MW|Malawi)$}i, 'Malawi', 'Malawi'],
  [ 'MX', qr{^(?:MX|Mexico|Mexiko)$}i, 'Mexico', 'Mexiko'],
  [ 'MY', qr{^(?:MY|Malaysia)$}i, 'Malaysia', 'Malaysia'],
  [ 'MZ', qr{^(?:MZ|Mozambique|Mosambik)$}i, 'Mozambique', 'Mosambik'],
  [ 'NA', qr{^(?:NA|Namibia)$}i, 'Namibia', 'Namibia'],
  [ 'NC', qr{^(?:NC|New Caledonia|Neukaledonien)$}i, 'New Caledonia', 'Neukaledonien'],
  [ 'NE', qr{^(?:NE|Niger)$}i, 'Niger', 'Niger'],
  [ 'NF', qr{^(?:NF|Norfolk Island|Norfolkinsel)$}i, 'Norfolk Island', 'Norfolkinsel'],
  [ 'NG', qr{^(?:NG|Nigeria)$}i, 'Nigeria', 'Nigeria'],
  [ 'NI', qr{^(?:NI|Nicaragua)$}i, 'Nicaragua', 'Nicaragua'],
  [ 'NL', qr{^(?:NL|Netherlands|Niederlande)$}i, 'Netherlands', 'Niederlande'],
  [ 'NO', qr{^(?:NO|Norway|Norwegen)$}i, 'Norway', 'Norwegen'],
  [ 'NP', qr{^(?:NP|Nepal)$}i, 'Nepal', 'Nepal'],
  [ 'NR', qr{^(?:NR|Nauru)$}i, 'Nauru', 'Nauru'],
  [ 'NU', qr{^(?:NU|Niue)$}i, 'Niue', 'Niue'],
  [ 'NZ', qr{^(?:NZ|New Zealand|Neuseeland)$}i, 'New Zealand', 'Neuseeland'],
  [ 'OM', qr{^(?:OM|Oman)$}i, 'Oman', 'Oman'],
  [ 'PA', qr{^(?:PA|Panama)$}i, 'Panama', 'Panama'],
  [ 'PE', qr{^(?:PE|Peru)$}i, 'Peru', 'Peru'],
  [ 'PF', qr{^(?:PF|French Polynesia|Französisch-Polynesien)$}i, 'French Polynesia', 'Französisch-Polynesien'],
  [ 'PG', qr{^(?:PG|Papua New Guinea|Papua-Neuguinea)$}i, 'Papua New Guinea', 'Papua-Neuguinea'],
  [ 'PH', qr{^(?:PH|Philippines|Philippinen)$}i, 'Philippines', 'Philippinen'],
  [ 'PK', qr{^(?:PK|Pakistan)$}i, 'Pakistan', 'Pakistan'],
  [ 'PL', qr{^(?:PL|Poland|Polen)$}i, 'Poland', 'Polen'],
  [ 'PM', qr{^(?:PM|Saint Pierre and Miquelon|Saint-Pierre und Miquelon)$}i, 'Saint Pierre and Miquelon', 'Saint-Pierre und Miquelon'],
  [ 'PN', qr{^(?:PN|Pitcairn|Pitcairninseln)$}i, 'Pitcairn', 'Pitcairninseln'],
  [ 'PR', qr{^(?:PR|Puerto Rico)$}i, 'Puerto Rico', 'Puerto Rico'],
  [ 'PS', qr{^(?:PS|Palestine, State of|Palästina)$}i, 'Palestine, State of', 'Palästina'],
  [ 'PT', qr{^(?:PT|Portugal)$}i, 'Portugal', 'Portugal'],
  [ 'PW', qr{^(?:PW|Palau)$}i, 'Palau', 'Palau'],
  [ 'PY', qr{^(?:PY|Paraguay)$}i, 'Paraguay', 'Paraguay'],
  [ 'QA', qr{^(?:QA|Qatar|Katar)$}i, 'Qatar', 'Katar'],
  [ 'RE', qr{^(?:RE|Réunion)$}i, 'Réunion', 'Réunion'],
  [ 'RO', qr{^(?:RO|Romania|Rumänien)$}i, 'Romania', 'Rumänien'],
  [ 'RS', qr{^(?:RS|Serbia|Serbien)$}i, 'Serbia', 'Serbien'],
  [ 'RU', qr{^(?:RU|Russian Federation|Russia|Russland)$}i, 'Russian Federation|Russia', 'Russland'],
  [ 'RW', qr{^(?:RW|Rwanda|Ruanda)$}i, 'Rwanda', 'Ruanda'],
  [ 'SA', qr{^(?:SA|Saudi Arabia|Saudi-Arabien)$}i, 'Saudi Arabia', 'Saudi-Arabien'],
  [ 'SB', qr{^(?:SB|Solomon Islands|Salomonen)$}i, 'Solomon Islands', 'Salomonen'],
  [ 'SC', qr{^(?:SC|Seychelles)$}i, 'Seychelles', 'Seychellen'],
  [ 'SD', qr{^(?:SD|Sudan)$}i, 'Sudan', 'Sudan'],
  [ 'SE', qr{^(?:SE|Sweden|Schweden)$}i, 'Sweden', 'Schweden'],
  [ 'SG', qr{^(?:SG|Singapore|Singapur)$}i, 'Singapore', 'Singapur'],
  [ 'SH', qr{^(?:SH|Saint Helena, Ascension and Tristan da Cunha)$}i, 'Saint Helena, Ascension and Tristan da Cunha', 'St. Helena'],
  [ 'SI', qr{^(?:SI|Slovenia|Slowenien)$}i, 'Slovenia', 'Slowenien'],
  [ 'SJ', qr{^(?:SJ|Svalbard and Jan Mayen|Spitzbergen und Jan Mayen)$}i, 'Svalbard and Jan Mayen', 'Spitzbergen und Jan Mayen'],
  [ 'SK', qr{^(?:SK|Slovakia|Slowakei)$}i, 'Slovakia', 'Slowakei'],
  [ 'SL', qr{^(?:SL|Sierra Leone)$}i, 'Sierra Leone', 'Sierra Leone'],
  [ 'SM', qr{^(?:SM|San Marino)$}i, 'San Marino', 'San Marino'],
  [ 'SN', qr{^(?:SN|Senegal)$}i, 'Senegal', 'Senegal'],
  [ 'SO', qr{^(?:SO|Somalia)$}i, 'Somalia', 'Somalia'],
  [ 'SR', qr{^(?:SR|Suriname)$}i, 'Suriname', 'Suriname'],
  [ 'SS', qr{^(?:SS|South Sudan|Südsudan)$}i, 'South Sudan', 'Südsudan'],
  [ 'ST', qr{^(?:ST|Sao Tome and Principe|São Tomé und Príncipe)$}i, 'Sao Tome and Principe', 'São Tomé und Príncipe'],
  [ 'SV', qr{^(?:SV|El Salvador)$}i, 'El Salvador', 'El Salvador'],
  [ 'SX', qr{^(?:SX|Sint Maarten \(Dutch part\)|Sint Maarten)$}i, 'Sint Maarten (Dutch part)', 'Sint Maarten'],
  [ 'SY', qr{^(?:SY|Syrian Arab Republic|Syrien)$}i, 'Syrian Arab Republic', 'Syrien'],
  [ 'SZ', qr{^(?:SZ|Eswatini)$}i, 'Eswatini', 'Swasiland'],
  [ 'TC', qr{^(?:TC|Turks and Caicos Islands|Turks- und Caicosinseln)$}i, 'Turks and Caicos Islands', 'Turks- und Caicosinseln'],
  [ 'TD', qr{^(?:TD|Chad|Tschad)$}i, 'Chad', 'Tschad'],
  [ 'TF', qr{^(?:TF|French Southern Territories|Französische Süd- und Antarktisgebiete)$}i, 'French Southern Territories', 'Französische Süd- und Antarktisgebiete'],
  [ 'TG', qr{^(?:TG|Togo)$}i, 'Togo', 'Togo'],
  [ 'TH', qr{^(?:TH|Thailand)$}i, 'Thailand', 'Thailand'],
  [ 'TJ', qr{^(?:TJ|Tajikistan|Tadschikistan)$}i, 'Tajikistan', 'Tadschikistan'],
  [ 'TK', qr{^(?:TK|Tokelau)$}i, 'Tokelau', 'Tokelau'],
  [ 'TL', qr{^(?:TL|Timor-Leste|Osttimor)$}i, 'Timor-Leste', 'Osttimor (Timor-Leste)'],
  [ 'TM', qr{^(?:TM|Turkmenistan)$}i, 'Turkmenistan', 'Turkmenistan'],
  [ 'TN', qr{^(?:TN|Tunisia|Tunesien)$}i, 'Tunisia', 'Tunesien'],
  [ 'TO', qr{^(?:TO|Tonga)$}i, 'Tonga', 'Tonga'],
  [ 'TR', qr{^(?:TR|Turkey|Türkei)$}i, 'Turkey', 'Türkei'],
  [ 'TT', qr{^(?:TT|Trinidad and Tobago|Trinidad und Tobago)$}i, 'Trinidad and Tobago', 'Trinidad und Tobago'],
  [ 'TV', qr{^(?:TV|Tuvalu)$}i, 'Tuvalu', 'Tuvalu'],
  [ 'TW', qr{^(?:TW|Taiwan, Province of China|Taiwan)$}i, 'Taiwan, Province of China', 'Taiwan'],
  [ 'TZ', qr{^(?:TZ|Tanzania, United Republic of|Tansania)$}i, 'Tanzania, United Republic of', 'Tansania'],
  [ 'UA', qr{^(?:UA|Ukraine)$}i, 'Ukraine', 'Ukraine'],
  [ 'UG', qr{^(?:UG|Uganda)$}i, 'Uganda', 'Uganda'],
  [ 'UM', qr{^(?:UM|United States Minor Outlying Islands)$}i, 'United States Minor Outlying Islands', 'United States Minor Outlying Islands'],
  [ 'US', qr{^(?:US|United States of America|Vereinigte Staaten|U\.?\s?S\.?\s?A\.?)$}i, 'United States of America', 'Vereinigte Staaten von Amerika'],
  [ 'UY', qr{^(?:UY|Uruguay)$}i, 'Uruguay', 'Uruguay'],
  [ 'UZ', qr{^(?:UZ|Uzbekistan|Usbekistan)$}i, 'Uzbekistan', 'Usbekistan'],
  [ 'VA', qr{^(?:VA|Holy See|Vatikanstadt)$}i, 'Holy See', 'Vatikanstadt'],
  [ 'VC', qr{^(?:VC|Saint Vincent and the Grenadines|St\. Vincent und die Grenadinen)$}i, 'Saint Vincent and the Grenadines', 'St. Vincent und die Grenadinen'],
  [ 'VE', qr{^(?:VE|Venezuela \(Bolivian Republic of\)|Venezuela)$}i, 'Venezuela (Bolivian Republic of)', 'Venezuela'],
  [ 'VG', qr{^(?:VG|Virgin Islands \(British\)|Britische Jungferninseln)$}i, 'Virgin Islands (British)', 'Britische Jungferninseln'],
  [ 'VI', qr{^(?:VI|Virgin Islands \(U\.?S\.?\)|Amerikanische Jungferninseln)$}i, 'Virgin Islands (U.S.)', 'Amerikanische Jungferninseln'],
  [ 'VN', qr{^(?:VN|Viet Nam|Vietnam)$}i, 'Viet Nam', 'Vietnam'],
  [ 'VU', qr{^(?:VU|Vanuatu)$}i, 'Vanuatu', 'Vanuatu'],
  [ 'WF', qr{^(?:WF|Wallis and Futuna|Wallis und Futuna)$}i, 'Wallis and Futuna', 'Wallis und Futuna'],
  [ 'WS', qr{^(?:WS|Samoa)$}i, 'Samoa', 'Samoa'],
  [ 'YE', qr{^(?:YE|Yemen|Jemen)$}i, 'Yemen', 'Jemen'],
  [ 'YT', qr{^(?:YT|Mayotte)$}i, 'Mayotte', 'Mayotte'],
  [ 'ZA', qr{^(?:ZA|South Africa|Südafrika)$}i, 'South Africa', 'Südafrika'],
  [ 'ZM', qr{^(?:ZM|Zambia|Sambia)$}i, 'Zambia', 'Sambia'],
  [ 'ZW', qr{^(?:ZW|Zimbabwe|Simbabwe)$}i, 'Zimbabwe', 'Simbabwe'],
);

sub map_name_to_alpha_2_code {
  my ($country) = @_;

  return undef if ($country // '') eq '';

  my $code = first { $country =~ $_->[1] } @alpha_2_mappings;
  return $code->[0] if $code;

  no warnings 'once';
  $::lxdebug->message(LXDebug::WARN(), "ISO3166::map_name_to_alpha_2_code: no mapping found for '$country'");

  return undef;
}

sub get_alpha_2_mappings {
  \@alpha_2_mappings;
}

1;
