#!/usr/bin/perl

$self->{texts} = {
  'Database update error:'      => 'Database update error:',
};

$self->{subs} = {
  'do_query'                    => 'do_query',
  'do_update'                   => 'do_update',
  'mydberror'                   => 'mydberror',
};

1;
