package SL::DB::IncomeStatementChDetailedGroups;

use strict;
use warnings;

use parent qw(SL::DB::Object);

# NOTE: the set up usually happens in the meta setup files, these files are auto
# generated by the script rose_auto_create_model.pl, since this is a view and
# not a regular table the script does not auto generate the meta setup files,
# therefore we are doing the set up here manually
__PACKAGE__->meta->table('income_statement_ch_detailed_groups');

__PACKAGE__->meta->columns(
  id          => { type => 'integer', not_null => 1 },
  description => { type => 'text' },
);

__PACKAGE__->meta->primary_key_columns([ 'id' ]);

__PACKAGE__->meta->allow_inline_column_values(1);

__PACKAGE__->meta->initialize;

__PACKAGE__->meta->make_manager_class;

1;

__END__

=pod

=encoding utf8

=head1 NAME

SL::DB::IncomeStatementChDetailedGroups - Rose model for the view income_statement_ch_detailed_groups

=cut
