package SL::DB::IncomeStatementChDetailedCategories;

use strict;
use warnings;

use parent qw(SL::DB::Object);

# NOTE: the set up usually happens in the meta setup files, these files are auto
# generated by the script rose_auto_create_model.pl, since this is a view and
# not a regular table the script does not auto generate the meta setup files,
# therefore we are doing the set up here manually
__PACKAGE__->meta->table('income_statement_ch_detailed_categories');

__PACKAGE__->meta->columns(
  id            => { type => 'integer', not_null => 1 },
  description   => { type => 'text' },
  account_range => { type => 'text' },
  group_id      => { type => 'integer' },
);

# QUESTION: what does allow_inline_column_values do?
__PACKAGE__->meta->allow_inline_column_values(1);

# QUESTION: does it make sense to define foreign constraints here,
# even though they are not defined on the actual view in the database?
__PACKAGE__->meta->foreign_keys(
  group => {
    class       => 'SL::DB::IncomeStatementChDetailedGroups',
    key_columns => { group_id => 'id' },
  },
);

__PACKAGE__->meta->primary_key_columns([ 'id' ]);

__PACKAGE__->meta->initialize;

# Creates get_all, get_all_count, get_all_iterator, delete_all and update_all.
__PACKAGE__->meta->make_manager_class;

1;

__END__

=pod

=encoding utf8

=head1 NAME

SL::DB::IncomeStatementChDetailedCategories - Rose model for the view income_statement_ch_detailed_categories

=cut
