diag("Create first Customer");

if(!$sel->get_title("Lx-Office Version 2.4.3 - Selenium - " . $lxtest->{db})){
  require_ok("../../begin/B004Login.t");
}

$sel->select_frame_ok("relative=up");
$sel->click_ok("link=Kunde erfassen");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});
$sel->title_is("Lx-Office Version 2.4.3 - Selenium - " . $lxtest->{db});
$sel->select_frame_ok("main_window");
$sel->click_ok("customernumber");
$sel->type_ok("customernumber", "001");
$sel->type_ok("greeting", "Firma");
$sel->type_ok("name", "Selenium-Testfirma1");
$sel->type_ok("department_1", "Einkauf");
$sel->type_ok("department_2", "extern");
$sel->type_ok("street", "Grummelburger 111");
$sel->type_ok("zipcode", "37115");
$sel->type_ok("city", "Musterstadt");
$sel->type_ok("country", "Germany");
$sel->type_ok("creditlimit", "100");
$sel->type_ok("discount", "5");
$sel->type_ok("account_number", "1");
$sel->select_ok("salesman_id", "label=Selenium");
$sel->type_ok("notes", "keine Bemerkungen");
$sel->click_ok("link=Lieferadresse");
$sel->click_ok("shipto_id");
$sel->select_ok("shipto_id", "label=Alle");
$sel->click_ok("//tr[1]/td/select/option[2]");
$sel->click_ok("shiptoname");
$sel->click_ok("shiptodepartment_1");
$sel->type_ok("shiptodepartment_1", "Einkauf");
$sel->type_ok("shiptostreet", "Donnerburger 12");
$sel->type_ok("shiptozipcode", "37115");
$sel->type_ok("shiptocity", "Musterstadt");
$sel->type_ok("shiptocountry", "Germany");
$sel->type_ok("shiptocontact", "Herr Mustermann");
$sel->type_ok("shiptophone", "0");
$sel->type_ok("shiptofax", "1");
$sel->type_ok("shiptoemail", "mustermann\@linet-services.de");
$sel->click_ok("link=Ansprechpartner");
$sel->click_ok("cp_greeting");
$sel->type_ok("cp_greeting", "Frau");
$sel->type_ok("cp_title", "Dr.");
$sel->type_ok("cp_abteilung", "Verkauf");
$sel->type_ok("cp_givenname", "Mechtilde");
$sel->type_ok("cp_name", "Grosshaupt");
$sel->type_ok("cp_phone1", "05528 111111111");
$sel->type_ok("cp_phone2", "05528 222222222");
$sel->type_ok("cp_fax", "05528 222222223");
$sel->type_ok("cp_mobile1", "05528 2222222224");
$sel->type_ok("cp_mobile2", "05528 2222222225");
$sel->type_ok("cp_satphone", "05528 2222222226");
$sel->type_ok("cp_satfax", "05528 2222222227");
$sel->type_ok("cp_project", "1");
$sel->type_ok("cp_email", "mustergrosshaupt\@linet-services.de");
$sel->type_ok("cp_privatphone", "05528 2222222220");
$sel->type_ok("cp_privatemail", "keine\@linet-services.de");
$sel->type_ok("cp_birthday", "05.09.1982");
$sel->click_ok("link=Lieferungen");
$sel->click_ok("delivery_id");
$sel->click_ok("action");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});

diag("Create second Customer");
$sel->title_is("Kunde erfassen - Lx-Office Version 2.4.3 - Selenium - " . $lxtest->{db});
$sel->select_frame_ok("relative=up");
$sel->click_ok("link=Kunde erfassen");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});
$sel->select_frame_ok("main_window");
$sel->click_ok("link=Rechnungsadresse");
$sel->click_ok("customernumber");
$sel->type_ok("customernumber", "2");
$sel->click_ok("greeting");
$sel->type_ok("greeting", "Herr");
$sel->type_ok("name", "TestMann2");
$sel->type_ok("street", "Goettingweg 3");
$sel->type_ok("zipcode", "38100");
$sel->type_ok("city", "Braunschweig");
$sel->type_ok("country", "Germany");
$sel->type_ok("phone", "0531 010101010101");
$sel->type_ok("email", "testmann\@linet-services.de");
$sel->click_ok("document.ct.action[1]");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});

diag("Create third Customer");
$sel->title_is("Kunde erfassen - Lx-Office Version 2.4.3 - Selenium - " . $lxtest->{db});
$sel->select_frame_ok("relative=up");
$sel->click_ok("link=Kunde erfassen");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});
$sel->select_frame_ok("main_window");
$sel->click_ok("customernumber");
$sel->type_ok("customernumber", "3");
$sel->click_ok("greeting");
$sel->type_ok("greeting", "Frau");
$sel->type_ok("name", "TestFrau3");
$sel->type_ok("department_1", "Outsourced");
$sel->type_ok("street", "Billighäuser 3444");
$sel->click_ok("street");
$sel->click_ok("zipcode");
$sel->type_ok("zipcode", "67899");
$sel->type_ok("city", "Brunnenberge");
$sel->type_ok("country", "Austria");
$sel->click_ok("document.ct.action[1]");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});
