diag("Create vendor");

if(!$sel->get_title("Lx-Office Version 2.4.3 - Selenium - " . $lxtest->{db})){
  require_ok("../../begin/B004Login.t");
}

$sel->select_frame_ok("relative=up");
$sel->click_ok("link=Lieferant erfassen");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});
diag("Create first vendor");
$sel->select_frame_ok("main_window");
$sel->click_ok("vendornumber");
$sel->type_ok("vendornumber", "1");
$sel->click_ok("selected_company_greeting");
$sel->select_ok("selected_company_greeting", "label=Firma");
$sel->click_ok("//option[2]");
$sel->click_ok("name");
$sel->type_ok("name", "TestLieferant1");
$sel->type_ok("department_1", "GossAus");
$sel->type_ok("street", "Berger 1");
$sel->type_ok("zipcode", "11990");
$sel->type_ok("city", "Drehmel");
$sel->type_ok("country", "Germany");
$sel->type_ok("contact", "Herr Custom");
$sel->type_ok("phone", "01234 56787902");
$sel->type_ok("fax", "01234 567879023");
$sel->type_ok("email", "custom\@linet-services.de");
$sel->type_ok("account_number", "2");
$sel->click_ok("obsolete");
$sel->click_ok("obsolete");
$sel->type_ok("notes", "keine Bemerkungen");
$sel->click_ok("link=Lieferadresse");
$sel->click_ok("shipto_id");
$sel->select_ok("shipto_id", "label=Alle");
$sel->click_ok("//tr[1]/td/select/option[2]");
$sel->click_ok("link=Ansprechpartner");
$sel->click_ok("cp_id");
$sel->click_ok("cp_id");
$sel->click_ok("cp_greeting");
$sel->click_ok("selected_cp_greeting");
$sel->select_ok("selected_cp_greeting", "label=Frau");
$sel->click_ok("//tr[2]/td/select/option[2]");
$sel->click_ok("cp_title");
$sel->click_ok("selected_cp_title");
$sel->click_ok("cp_title");
$sel->type_ok("cp_title", "Diplom Meterologin");
$sel->click_ok("cp_abteilung");
$sel->type_ok("cp_title", "Dipl. Inf.");
$sel->click_ok("cp_title");
$sel->click_ok("cp_title");
$sel->type_ok("cp_title", "Dipl. Ing.");
$sel->click_ok("cp_abteilung");
$sel->type_ok("cp_abteilung", "Externes");
$sel->type_ok("cp_givenname", "Hildegunde");
$sel->type_ok("cp_name", "Riess");
$sel->type_ok("cp_phone1", "0111 222333444 5");
$sel->click_ok("cp_birthday");
$sel->type_ok("cp_birthday", "12.03.1964");
$sel->click_ok("link=Lieferungen");
$sel->click_ok("action");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});
$sel->click_ok("link=Rechnungsadresse");
$sel->click_ok("document.ct.action[1]");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});
diag("Create second vendor");
$sel->click_ok("vendornumber");
$sel->type_ok("vendornumber", "2");
$sel->click_ok("greeting");
$sel->click_ok("selected_company_greeting");
$sel->select_ok("selected_company_greeting", "label=Firma");
$sel->click_ok("//option[2]");
$sel->click_ok("name");
$sel->type_ok("name", "TestLieferant2");
$sel->type_ok("department_1", "Verkauf");
$sel->type_ok("department_2", "Orga");
$sel->type_ok("street", "Wlkenweg 3");
$sel->type_ok("zipcode", "09090");
$sel->type_ok("city", "Brummbach");
$sel->click_ok("city");
$sel->type_ok("city", "Markt Brummbach");
$sel->click_ok("country");
$sel->type_ok("country", "Germany");
$sel->click_ok("document.ct.action[1]");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});
diag("Create third vendor");
$sel->click_ok("link=Rechnungsadresse");
$sel->click_ok("vendornumber");
$sel->type_ok("vendornumber", "3");
$sel->click_ok("selected_company_greeting");
$sel->select_ok("selected_company_greeting", "label=Firma");
$sel->click_ok("//option[2]");
$sel->type_ok("name", "TestFirma3 GmbH");
$sel->type_ok("fax", "03232 7272727273");
$sel->type_ok("creditlimit", "50000");
$sel->type_ok("discount", "10");
$sel->click_ok("link=Lieferadresse");
$sel->click_ok("shiptoname");
$sel->type_ok("shiptoname", "TestFirma3 GmbH");
$sel->type_ok("shiptodepartment_1", "Vertrieb");
$sel->type_ok("shiptostreet", "Grummelsburger  1423");
$sel->type_ok("shiptozipcode", "40000");
$sel->type_ok("shiptocity", "Hansastadt");
$sel->type_ok("shiptocountry", "Germany");
$sel->type_ok("shiptocontact", "Herr Baumann von Clausen");
$sel->type_ok("shiptophone", "03232 7272727272");
$sel->type_ok("shiptofax", "03232 7272727273");
$sel->type_ok("shiptoemail", "baumann\@linet-services.de");
$sel->click_ok("link=Ansprechpartner");
$sel->click_ok("selected_cp_greeting");
$sel->click_ok("cp_greeting");
$sel->type_ok("cp_greeting", "Herr");
$sel->type_ok("cp_abteilung", "Vertrieb");
$sel->type_ok("cp_givenname", "Dietmar");
$sel->type_ok("cp_name", "Baumann von Clausen");
$sel->type_ok("cp_phone1", "03232 7272727272");
$sel->type_ok("cp_fax", "03232 7272727273");
$sel->type_ok("cp_birthday", "14.05.1971");
$sel->click_ok("link=Lieferungen");
$sel->click_ok("document.ct.action[1]");
$sel->wait_for_page_to_load_ok($lxtest->{timeout});

