#!/usr/bin/perl

$self->{texts} = {
  'Database update error:'      => 'Fehler beim Datenbankupgrade:',
  'Number of entries changed: #1' => 'Anzahl geänderter Einträge: #1',
};

$self->{subs} = {
  'do_query'                    => 'do_query',
  'do_update'                   => 'do_update',
  'mydberror'                   => 'mydberror',
};

1;
