#!/usr/bin/perl

$self->{texts} = {
  'Database update error:'      => 'Fehler beim Datenbankupgrade:',
};

$self->{subs} = {
  'do_query'                    => 'do_query',
  'do_update'                   => 'do_update',
  'mydberror'                   => 'mydberror',
  'print_3804_already_exists'   => 'print_3804_already_exists',
  'print_past_booking_warning'  => 'print_past_booking_warning',
  'weiter'                      => 'continue',
};

1;
