#!/usr/bin/perl

$self->{texts} = {
  'Database update error:'      => 'Fehler beim Datenbankupgrade:',
};

$self->{subs} = {
  'create_tables'               => 'create_tables',
  'do_copy'                     => 'do_copy',
  'do_query'                    => 'do_query',
  'mydberror'                   => 'mydberror',
};

1;
