#!/bin/sh
ln -s dispatcher.pl ar.pl
ln -s dispatcher.pl am.pl
ln -s dispatcher.pl bp.pl
ln -s dispatcher.pl login.pl
ln -s dispatcher.pl todo.pl
ln -s dispatcher.pl gl.pl
ln -s dispatcher.pl ir.pl
ln -s dispatcher.pl ct.pl
ln -s dispatcher.pl dn.pl
ln -s dispatcher.pl do.pl
ln -s dispatcher.pl oe.pl
ln -s dispatcher.pl wh.pl
ln -s dispatcher.pl ap.pl
ln -s dispatcher.pl rp.pl
ln -s dispatcher.pl ca.pl
ln -s dispatcher.pl ustva.pl
ln -s dispatcher.pl is.pl
ln -s dispatcher.pl amtemplates.pl
ln -s dispatcher.pl ic.pl
