if(!defined $sel) {
  require "t/selenium/AllTests.t";
  init_server("singlefileonly",$0);
  exit(0);
}
diag("Create offers");
SKIP: {
  start_login();
  
  $sel->click_ok("link=Angebot erfassen");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->select_frame_ok("main_window");
  $sel->select_ok("cp_id", "label=Grosshaupt (Verkauf)");
  $sel->select_ok("customer", "label=TestFrau3");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->select_ok("customer", "label=Selenium-Testfirma1");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->select_ok("cp_id", "label=Grosshaupt (Verkauf)");
  $sel->type_ok("shipvia", "per pedes");
  $sel->type_ok("transaction_description", "alpha");
  $sel->type_ok("quonumber", "1");
  $sel->select_ok("globalproject_id", "label=1001");
  $sel->click_ok("cb_show_details");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->type_ok("partnumber_1", "1");
#   TODO: {
#     local $TODO = "Popups werden von Selenium noch nicht unterstützt!";
#     $sel->click_ok("//button[\@type='button']");
#     $sel->wait_for_page_to_load_ok($lxtest->{timeout});
#   }
  $sel->click_ok("update_button");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->click_ok("action");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->click_ok("update_button");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->click_ok("document.oe.action[5]");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->click_ok("document.oe.action[6]");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->select_ok("customer", "label=TestFrau3");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->type_ok("partnumber_1", "991");
  $sel->click_ok("update_button");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->type_ok("qty_1", "5");
  $sel->select_ok("sellprice_pg_1", "label=SeleniumTestPreisgruppe1");
  $sel->click_ok("update_button");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->click_ok("taxincluded");
  $sel->select_ok("payment_id", "label=Schnellzahler/Skonto");
  $sel->click_ok("update_button");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->click_ok("document.oe.action[6]");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->select_ok("customer", "label=TestMann2");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->type_ok("partnumber_1", "1");
  $sel->click_ok("update_button");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->click_ok("action");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->select_ok("sellprice_pg_1", "label=SeleniumTestPreisgruppe1");
  $sel->type_ok("qty_1", "19");
  $sel->select_ok("payment_id", "label=Schnellzahler/Skonto");
  $sel->click_ok("update_button");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
  $sel->click_ok("document.oe.action[6]");
  $sel->wait_for_page_to_load_ok($lxtest->{timeout});
};
1;