-- DATEV SKR03
-- Office-Service http://www.officeservice-einberger.de
--
INSERT INTO gifi (accno,description) VALUES ('0001', 'Aufwand Geschäftsbetrieb');
INSERT INTO gifi (accno,description) VALUES ('0002', 'Aufwendungen Umstellung a.d.Euro');
INSERT INTO gifi (accno,description) VALUES ('0010', 'Konzession,gewerb.Schutzre.u.Werten');
INSERT INTO gifi (accno,description) VALUES ('0015', 'Konzessionen');
INSERT INTO gifi (accno,description) VALUES ('0020', 'Gewerbl.Schutzrechte');
INSERT INTO gifi (accno,description) VALUES ('0025', 'Ähnl.Rechte und Werte');
INSERT INTO gifi (accno,description) VALUES ('0027', 'EDV-Software');
INSERT INTO gifi (accno,description) VALUES ('0030', 'Liz.a.gewerbl.Schutzre.u.ähnl.Re.u.Wert.');
INSERT INTO gifi (accno,description) VALUES ('0035', 'Geschäfts-oder Firmenwert');
INSERT INTO gifi (accno,description) VALUES ('0038', 'Anzahlungen a.Geschäft-o.Firmenwert');
INSERT INTO gifi (accno,description) VALUES ('0039', 'Anz.a.immaterielle Vermögsgegenstän');
INSERT INTO gifi (accno,description) VALUES ('0040', 'Verschmelzungsmehrwert');
INSERT INTO gifi (accno,description) VALUES ('0050', 'Grundstücke,grundstücksgl.Rechte..');
INSERT INTO gifi (accno,description) VALUES ('0060', 'Grundstücke u.grundstgl.Rech.o.Baut');
INSERT INTO gifi (accno,description) VALUES ('0065', 'Unbebaute Grundstücke');
INSERT INTO gifi (accno,description) VALUES ('0070', 'Grundstücksgl.Re.(Erbau-,Dauerwohnre.)');
INSERT INTO gifi (accno,description) VALUES ('0075', 'Grundstücke m.Substanzverzehr');
INSERT INTO gifi (accno,description) VALUES ('0079', 'Anz.a.Grundst.u.grundstücksgl.Re.ohne Bauten');
INSERT INTO gifi (accno,description) VALUES ('0080', 'Bauten a.eig. Grundstücken,Grgl.Rec');
INSERT INTO gifi (accno,description) VALUES ('0085', 'Grundstückswert eige.bebau.Grundst.');
INSERT INTO gifi (accno,description) VALUES ('0090', 'Geschäftsbauten');
INSERT INTO gifi (accno,description) VALUES ('0100', 'Fabrikbauten');
INSERT INTO gifi (accno,description) VALUES ('0110', 'Garagen');
INSERT INTO gifi (accno,description) VALUES ('0111', 'Außenanlagen');
INSERT INTO gifi (accno,description) VALUES ('0112', 'Hof-und Wegebefestigung');
INSERT INTO gifi (accno,description) VALUES ('0113', 'Einr.f.Geschäfts-u.Fabrikbauten');
INSERT INTO gifi (accno,description) VALUES ('0115', 'Andere Bauten');
INSERT INTO gifi (accno,description) VALUES ('0120', 'Geschäfts-,Fabrik-,andere Bau.imBau');
INSERT INTO gifi (accno,description) VALUES ('0129', 'Anz.Geschäfts-,Fabrik u. and.Bauten');
INSERT INTO gifi (accno,description) VALUES ('0140', 'Wohnbauten');
INSERT INTO gifi (accno,description) VALUES ('0145', 'Garagen');
INSERT INTO gifi (accno,description) VALUES ('0146', 'Aussenanlagen');
INSERT INTO gifi (accno,description) VALUES ('0147', 'Hof-u.Wegebefestigungen');
INSERT INTO gifi (accno,description) VALUES ('0148', 'Einr.f.Wohnbauten');
INSERT INTO gifi (accno,description) VALUES ('0150', 'Wohnbauten im Bau');
INSERT INTO gifi (accno,description) VALUES ('0159', 'Anz.a.Wohnb.a.eig.Grundst.u.grundstgl.Re.');
INSERT INTO gifi (accno,description) VALUES ('0160', 'Bauten auf fremden Grundstücken');
INSERT INTO gifi (accno,description) VALUES ('0165', 'Geschäftsbauten');
INSERT INTO gifi (accno,description) VALUES ('0170', 'Fabrikbauten');
INSERT INTO gifi (accno,description) VALUES ('0175', 'Garagen');
INSERT INTO gifi (accno,description) VALUES ('0176', 'Außenanlage');
INSERT INTO gifi (accno,description) VALUES ('0177', 'Hof-u.Wegebefestigungen');
INSERT INTO gifi (accno,description) VALUES ('0178', 'Einr.f.Geschäfts-u.Fabrikbauten');
INSERT INTO gifi (accno,description) VALUES ('0179', 'Andere Bauten');
INSERT INTO gifi (accno,description) VALUES ('0180', 'Geschäfts,-Farbik-u.and.Bauten i.Bau');
INSERT INTO gifi (accno,description) VALUES ('0189', 'Anz.a.Geschäfts-,Fabr.-u.and.Bauten a.fremd.Grundst.');
INSERT INTO gifi (accno,description) VALUES ('0190', 'Wohnbauten');
INSERT INTO gifi (accno,description) VALUES ('0191', 'Garagen');
INSERT INTO gifi (accno,description) VALUES ('0192', 'Aussenanlagen');
INSERT INTO gifi (accno,description) VALUES ('0193', 'Hof-u.Wegebefestigung');
INSERT INTO gifi (accno,description) VALUES ('0194', 'Einr.für Wohnbauten');
INSERT INTO gifi (accno,description) VALUES ('0195', 'Wohnbauten i.Bau');
INSERT INTO gifi (accno,description) VALUES ('0199', 'Anz.a.Wohnb.a.fremd.Grundst.');
INSERT INTO gifi (accno,description) VALUES ('0200', 'Techn.Anlagen und Maschinen');
INSERT INTO gifi (accno,description) VALUES ('0210', 'Maschinen');
INSERT INTO gifi (accno,description) VALUES ('0220', 'Maschinengebundene Werkzeuge');
INSERT INTO gifi (accno,description) VALUES ('0240', 'Maschinelle Anlagen');
INSERT INTO gifi (accno,description) VALUES ('0260', 'Transportanlagen u.ähnl.');
INSERT INTO gifi (accno,description) VALUES ('0280', 'Betriebsvorrichtung');
INSERT INTO gifi (accno,description) VALUES ('0290', 'Techn.Anlagen u.Maschinen im Bau');
INSERT INTO gifi (accno,description) VALUES ('0299', 'Anz.a.techn.Anlagen und Maschinen');
INSERT INTO gifi (accno,description) VALUES ('0300', 'Andere Anlagen,Betrieb-Geschäftsaus');
INSERT INTO gifi (accno,description) VALUES ('0310', 'Andere Anlagen');
INSERT INTO gifi (accno,description) VALUES ('0320', 'PKW');
INSERT INTO gifi (accno,description) VALUES ('0350', 'LKW');
INSERT INTO gifi (accno,description) VALUES ('0380', 'Sonst.Transportmittel');
INSERT INTO gifi (accno,description) VALUES ('0400', 'Betriebsausstattung');
INSERT INTO gifi (accno,description) VALUES ('0410', 'Geschäftsausstattung');
INSERT INTO gifi (accno,description) VALUES ('0420', 'Büroeinrichtung');
INSERT INTO gifi (accno,description) VALUES ('0430', 'Ladeneinrichtung');
INSERT INTO gifi (accno,description) VALUES ('0440', 'Werkzeuge');
INSERT INTO gifi (accno,description) VALUES ('0450', 'Einbauten');
INSERT INTO gifi (accno,description) VALUES ('0460', 'Gerüst-u.Schalungsmaterial');
INSERT INTO gifi (accno,description) VALUES ('0480', 'Geringwertige Wirtschaftsg.b.800DM');
INSERT INTO gifi (accno,description) VALUES ('0490', 'Sons.Betriebs- Geschäftsausstattung');
INSERT INTO gifi (accno,description) VALUES ('0498', 'And. Anlagen,Betrieb/Geschäf.im Bau');
INSERT INTO gifi (accno,description) VALUES ('0499', 'Anz.and.Anlagen,Betrieb.Geschäftsau');
INSERT INTO gifi (accno,description) VALUES ('0500', 'Anteile a.verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('0504', 'Ant.a.herr.o.m.Mehrh.bet.Ges.schaft');
INSERT INTO gifi (accno,description) VALUES ('0505', 'Ausleihung an verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('0510', 'Beteiligungen');
INSERT INTO gifi (accno,description) VALUES ('0513', 'Typisch stille Beteiligungen');
INSERT INTO gifi (accno,description) VALUES ('0516', 'Atypische stille Beteiligungen');
INSERT INTO gifi (accno,description) VALUES ('0517', 'And.Beteilig.an Kapitalgesellsch.');
INSERT INTO gifi (accno,description) VALUES ('0518', 'And.Beteilig.an Personengesellsch.');
INSERT INTO gifi (accno,description) VALUES ('0519', 'Beteilig.einer GmbH&Co.KGa.ein.Kompl.GmbH');
INSERT INTO gifi (accno,description) VALUES ('0520', 'Ausl.a.Untern.m.Beteiligungsverhält');
INSERT INTO gifi (accno,description) VALUES ('0525', 'Wertpapiere des Anlagevermögens');
INSERT INTO gifi (accno,description) VALUES ('0530', 'Wertpap.m.Gewinnbeteiligungsanspr.');
INSERT INTO gifi (accno,description) VALUES ('0535', 'Festverzinsliche Wertpapiere');
INSERT INTO gifi (accno,description) VALUES ('0540', 'Sonstige Ausleihungen');
INSERT INTO gifi (accno,description) VALUES ('0550', 'Darlehen');
INSERT INTO gifi (accno,description) VALUES ('0570', 'Genossenschaftsant.z.langfr.Verbleib');
INSERT INTO gifi (accno,description) VALUES ('0580', 'Ausleihungen an Gesellschafter');
INSERT INTO gifi (accno,description) VALUES ('0590', 'Ausleihungen an nahe stehende Personen');
INSERT INTO gifi (accno,description) VALUES ('0595', 'Rückdeckansp.Lebensvers.langf.Verbl');
INSERT INTO gifi (accno,description) VALUES ('0600', 'Anleihen-nicht konvertibel');
INSERT INTO gifi (accno,description) VALUES ('0601', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0605', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0610', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0615', 'Anleihen konvertibel');
INSERT INTO gifi (accno,description) VALUES ('0616', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0620', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0625', '- Restlaufzeit gösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0630', 'Verbindl.gegenüber Kreditinstituten');
INSERT INTO gifi (accno,description) VALUES ('0631', '- Restlaufzeit b.1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0640', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0650', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0660', 'Vblk.geg.Kreditinst.aus TZ-Verträgen');
INSERT INTO gifi (accno,description) VALUES ('0661', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0670', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0680', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0690', '(fr.i.Bilanz k.Restlaufzeitvermerk');
INSERT INTO gifi (accno,description) VALUES ('0699', 'Gegenkonto 630-689 b.Auft.d.Konten 690-698');
INSERT INTO gifi (accno,description) VALUES ('0700', 'Verbind.gegenüber verb.Unternehmern');
INSERT INTO gifi (accno,description) VALUES ('0701', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0705', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0710', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0715', 'Vblk.geg.Untern.m.denen ein Beteiligungsverh.best.');
INSERT INTO gifi (accno,description) VALUES ('0716', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0720', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0725', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0730', 'Vblk.geg.Gesellschaftern');
INSERT INTO gifi (accno,description) VALUES ('0731', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0740', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0750', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0755', 'Vblk.geg.Gesellsch.f.offene Ausschüttungen');
INSERT INTO gifi (accno,description) VALUES ('0760', 'Darl.typ.stiller Gesellschafter');
INSERT INTO gifi (accno,description) VALUES ('0761', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0764', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0767', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0770', 'Darlehen atyp.stiller Gesellsch.');
INSERT INTO gifi (accno,description) VALUES ('0771', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0774', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0777', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0780', 'Partiarische Darlehen');
INSERT INTO gifi (accno,description) VALUES ('0781', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0784', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0787', '- Restlaufzeit über 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('0790', 'fr.in Bilanz k.Restlaufzeitvermerk');
INSERT INTO gifi (accno,description) VALUES ('0799', 'Gegenk.730-789 b.Auft.d.Konten 790-798');
INSERT INTO gifi (accno,description) VALUES ('0800', 'Gezeichnetes Kapital');
INSERT INTO gifi (accno,description) VALUES ('0801', 'Ausst.Einl.a.gez.Kapital n.eingef.(Aktivausw.)');
INSERT INTO gifi (accno,description) VALUES ('0810', '');
INSERT INTO gifi (accno,description) VALUES ('0840', 'Kapitalrücklage');
INSERT INTO gifi (accno,description) VALUES ('0846', 'Gesetzliche Rücklage');
INSERT INTO gifi (accno,description) VALUES ('0850', 'Rücklage für eigene Anteile');
INSERT INTO gifi (accno,description) VALUES ('0851', 'Satzungsmäßige Rücklagen');
INSERT INTO gifi (accno,description) VALUES ('0860', 'Gewinnvortrag vor Verwendung');
INSERT INTO gifi (accno,description) VALUES ('0868', 'Verlustvortrag vor Verwendung');
INSERT INTO gifi (accno,description) VALUES ('0869', 'Vortrag auf neue Rechnungen (Bilanz)');
INSERT INTO gifi (accno,description) VALUES ('0870', 'Festkapital');
INSERT INTO gifi (accno,description) VALUES ('0880', 'Variables Kapital');
INSERT INTO gifi (accno,description) VALUES ('0890', 'Gesellschafter-Darlehen');
INSERT INTO gifi (accno,description) VALUES ('0900', 'Kommandit-Kapital');
INSERT INTO gifi (accno,description) VALUES ('0910', 'Verlustausgleichskonto');
INSERT INTO gifi (accno,description) VALUES ('0920', 'Gesellschafter-Darlehen');
INSERT INTO gifi (accno,description) VALUES ('0930', 'Sonderposten mit Rücklagenanteil stfr.Rückl.');
INSERT INTO gifi (accno,description) VALUES ('0931', 'Sopo m.Rückl.ant.nach §6b EstG');
INSERT INTO gifi (accno,description) VALUES ('0932', 'Sopo m.Rückl.ant.Abschn.35 EstR');
INSERT INTO gifi (accno,description) VALUES ('0935', 'Sopo aus Währungsumstellung Euro');
INSERT INTO gifi (accno,description) VALUES ('0947', 'Sopo m.Rückl.ant. §7g Abs.1 EstG');
INSERT INTO gifi (accno,description) VALUES ('0948', 'Sopo m.Rückl.ant. §7g Abs.3,7 EstG');
INSERT INTO gifi (accno,description) VALUES ('0949', 'Sopo f.Zuschüsse u.Zulagen');
INSERT INTO gifi (accno,description) VALUES ('0950', 'Rückst.f.Pensionen u.ähnl.Verpflichtungen');
INSERT INTO gifi (accno,description) VALUES ('0955', 'Steuerrückstellung');
INSERT INTO gifi (accno,description) VALUES ('0957', 'Gewerbesteuerrückstellung');
INSERT INTO gifi (accno,description) VALUES ('0963', 'Körperschaftssteuerrückstellung');
INSERT INTO gifi (accno,description) VALUES ('0969', 'Rückstellung für latente Steuern');
INSERT INTO gifi (accno,description) VALUES ('0970', 'Sonstige Rückstellungen');
INSERT INTO gifi (accno,description) VALUES ('0971', 'Rückst.f.unterl.Aufw.f.Instandh.,Nachh.i.d.erst.drei Mt.');
INSERT INTO gifi (accno,description) VALUES ('0972', 'Rückst.f.unterl.Aufw.f.Instandh.,Nachh.inn.d.4-12.Mt.');
INSERT INTO gifi (accno,description) VALUES ('0973', 'Rückst.f.Abraum-u.Abfallbeseitigung');
INSERT INTO gifi (accno,description) VALUES ('0974', 'Rückstellungen für Gewährleistungen Gegenkto.4970');
INSERT INTO gifi (accno,description) VALUES ('0976', 'Rücks.f.drohe.Verl.schweb.Geschäft');
INSERT INTO gifi (accno,description) VALUES ('0977', 'Rücks.f.Abschluß-u.Prüfungskosten');
INSERT INTO gifi (accno,description) VALUES ('0978', 'Aufwandsrückstellungen gem.§249 (2)');
INSERT INTO gifi (accno,description) VALUES ('0979', 'Rückst.f.Umweltschutz');
INSERT INTO gifi (accno,description) VALUES ('0980', 'Aktive Rechnungsabgrenzung');
INSERT INTO gifi (accno,description) VALUES ('0983', 'Abgrenzung aktive latente Steuern');
INSERT INTO gifi (accno,description) VALUES ('0984', 'Als Aufw.berücks.Zölle u.Verbrauchsst.a.Vorräte');
INSERT INTO gifi (accno,description) VALUES ('0985', 'Als Aufw.berücks.Ust.auf Anzahlungen');
INSERT INTO gifi (accno,description) VALUES ('0986', 'Damnum/Disagio');
INSERT INTO gifi (accno,description) VALUES ('0990', 'Passive Rechnungsabgrenzung');
INSERT INTO gifi (accno,description) VALUES ('0992', 'Wertberichtigungen z.unterjähhr.Kostenver.f.BWA');
INSERT INTO gifi (accno,description) VALUES ('0996', 'Pauschalwertb.m.Restlaufzeit bis 1J.');
INSERT INTO gifi (accno,description) VALUES ('0997', 'PWB a.Ford.m.einer RLZ v.mehr als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('0998', 'Einzelwertber.m.Restlaufzeit bis.1 J.');
INSERT INTO gifi (accno,description) VALUES ('0999', 'Einzelwertber.a.Ford.m.einer RLZ v.mehr als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1000', 'Kasse');
INSERT INTO gifi (accno,description) VALUES ('1100', 'Postbank');
INSERT INTO gifi (accno,description) VALUES ('1200', 'Bank');
INSERT INTO gifi (accno,description) VALUES ('1300', 'Wechsel a. Lieferungen u.Leistungen');
INSERT INTO gifi (accno,description) VALUES ('1301', '- Restlaufzeit b.1Jahr');
INSERT INTO gifi (accno,description) VALUES ('1302', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1305', 'Wechsel a.Lief.u.Leist.,bundesbankfähig');
INSERT INTO gifi (accno,description) VALUES ('1310', 'Besitzwechsel geg.verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('1311', '- Restlaufzeit b.1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1312', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1315', 'Besitzwechsel geg.verb.Untern.,bundesbankfähig');
INSERT INTO gifi (accno,description) VALUES ('1320', 'Besitzw.geg.Untern.m.Beteiligungsve');
INSERT INTO gifi (accno,description) VALUES ('1321', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1322', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1325', 'Besitzwechsel geg.Untern.m.denen e.Beteilig.Verh.best.bbf');
INSERT INTO gifi (accno,description) VALUES ('1327', 'Finanzwechsel');
INSERT INTO gifi (accno,description) VALUES ('1329', 'And.Wertpap.m.unwesentl.Wertschwank.i.S.Textz.18DRS 2');
INSERT INTO gifi (accno,description) VALUES ('1330', 'Schecks (Eingang)');
INSERT INTO gifi (accno,description) VALUES ('1340', 'Anteile verb.Untern.-Umlaufvermögen');
INSERT INTO gifi (accno,description) VALUES ('1344', 'Anteil an herr.od.m.betei.Gesellschaft');
INSERT INTO gifi (accno,description) VALUES ('1345', 'Eigene Anteile');
INSERT INTO gifi (accno,description) VALUES ('1348', 'Sonstige Wertpapiere');
INSERT INTO gifi (accno,description) VALUES ('1349', 'Wertpapieranl.i.Rahmen d.kurzfr.Finanzdisposition');
INSERT INTO gifi (accno,description) VALUES ('1350', 'GmbH-Anteile z.kurzfr.Verbleib');
INSERT INTO gifi (accno,description) VALUES ('1352', 'Genossenschaftsant.z.kurzfr.Verbleib');
INSERT INTO gifi (accno,description) VALUES ('1355', 'Anspr.a.Rückdeckungsvers.');
INSERT INTO gifi (accno,description) VALUES ('1360', 'Geldtransit');
INSERT INTO gifi (accno,description) VALUES ('1370', 'Verrechnungskto.f.Gewinnerm.§4/3 EStG,ergebniswirks.');
INSERT INTO gifi (accno,description) VALUES ('1371', 'Verrechnungskto.f.Gewinnerm.§4/3 EStG,n.ergebniswirks.');
INSERT INTO gifi (accno,description) VALUES ('1380', 'Überleitungskonto Kostenstelle');
INSERT INTO gifi (accno,description) VALUES ('1390', 'Verrechnungskonto Ist-Versteuerung');
INSERT INTO gifi (accno,description) VALUES ('1400', 'Ford. a.Lieferungen und Leistungen');
INSERT INTO gifi (accno,description) VALUES ('1401', 'Ford.a.Lieferungen und Leistungen');
INSERT INTO gifi (accno,description) VALUES ('1410', 'Ford.a.Lief.u.Leist. ohne Kontokorrent');
INSERT INTO gifi (accno,description) VALUES ('1450', 'Ford.n.§11(1)2EStG f.§4/3 EStG');
INSERT INTO gifi (accno,description) VALUES ('1451', 'Ford.a.Lief.u.Leist.ohn.Kontok.-RLZ b.1Jahr');
INSERT INTO gifi (accno,description) VALUES ('1455', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1460', 'Zweifelhafte Forderungen');
INSERT INTO gifi (accno,description) VALUES ('1461', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1465', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1470', 'Forder.a.Liefe.u.Leis.geg.verb.Unte');
INSERT INTO gifi (accno,description) VALUES ('1471', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1475', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1478', 'Wertb.a.Ford.m.Rest. bis 1j.geg.verb.Unt');
INSERT INTO gifi (accno,description) VALUES ('1479', 'Wertber.a.Ford.m.e.RLZ v.mehr als 1J geg.verb.Untern.');
INSERT INTO gifi (accno,description) VALUES ('1480', 'Ford. Lief.u.Leis.geg.Untern.m.Beteiligve');
INSERT INTO gifi (accno,description) VALUES ('1481', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1485', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1488', 'Wertb.a.Ford.m.Rest.bis 1j.Beteiligungs');
INSERT INTO gifi (accno,description) VALUES ('1489', 'Wertber.a.Ford.m.e.RLZ v.mehr a.1J geg.Untern.m.Bet.verh.');
INSERT INTO gifi (accno,description) VALUES ('1490', 'Forderung a.Leis.u.Lief.geg.Gesells');
INSERT INTO gifi (accno,description) VALUES ('1491', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1495', '- Restlaufzeit gösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1498', 'Gegenk.zu sonst.VG b.Buchungen ü.Debitorenkonto');
INSERT INTO gifi (accno,description) VALUES ('1499', 'Gegenk. 1451-1497 b.Aufteilung Debiorenkonto');
INSERT INTO gifi (accno,description) VALUES ('1500', 'Sonstige Vermögensgegenstände');
INSERT INTO gifi (accno,description) VALUES ('1501', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1502', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1503', 'Forde.geg.Vorstandsm.u.Geschäftsfüh RLZ b.1J');
INSERT INTO gifi (accno,description) VALUES ('1504', 'Ford.geg.Vorstandsmitgl.u.Geschäftsf. RLZ > 1 J.');
INSERT INTO gifi (accno,description) VALUES ('1505', 'Ford.geg.Aufsichtsrats-u.Beiratsmitgl. RLZ b.1J.');
INSERT INTO gifi (accno,description) VALUES ('1506', 'Ford.geg.Aufsichtsrats-u.Beiratsmitgl. RLZ > 1 J.');
INSERT INTO gifi (accno,description) VALUES ('1507', 'Ford.geg.Gesellschafter RLZ bis 1 J.');
INSERT INTO gifi (accno,description) VALUES ('1508', 'Forderungen gegen Gesellschafter RLZ > 1J');
INSERT INTO gifi (accno,description) VALUES ('1510', 'Geleistete Anzahlung auf Vorräte');
INSERT INTO gifi (accno,description) VALUES ('1511', 'Geleistete Anzahlungen 7%');
INSERT INTO gifi (accno,description) VALUES ('1517', 'Geleistete Anzahlung 16%');
INSERT INTO gifi (accno,description) VALUES ('1521', 'Agenturwarenabrechnung');
INSERT INTO gifi (accno,description) VALUES ('1525', 'Kautionen');
INSERT INTO gifi (accno,description) VALUES ('1526', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1527', '- Restlaufzeit > 1 J.');
INSERT INTO gifi (accno,description) VALUES ('1530', 'Forderungen aus Lohn-u.Gehaltsabrechnung');
INSERT INTO gifi (accno,description) VALUES ('1531', '- Restlaufzeit b.1J.');
INSERT INTO gifi (accno,description) VALUES ('1537', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1540', 'Steuerüberzahlungen');
INSERT INTO gifi (accno,description) VALUES ('1542', 'Steuererstattungsanspr.gegenüber and.EG-Länd.');
INSERT INTO gifi (accno,description) VALUES ('1543', 'Ford.a.d.Finanzamt a.abgef.Bauabzugsbetrag');
INSERT INTO gifi (accno,description) VALUES ('1545', 'Umsatzsteuerforderungen');
INSERT INTO gifi (accno,description) VALUES ('1547', 'Ford.aus entrichteten Verbrauchsteuern');
INSERT INTO gifi (accno,description) VALUES ('1548', 'Vorsteuer im Folgejahr abziehbar');
INSERT INTO gifi (accno,description) VALUES ('1549', 'Körperschaftsteuerrückforderung');
INSERT INTO gifi (accno,description) VALUES ('1550', 'Darlehen');
INSERT INTO gifi (accno,description) VALUES ('1551', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1555', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1556', 'Nachträgl.abziehb.Vorst.,§15aUStG,bewegl.WG');
INSERT INTO gifi (accno,description) VALUES ('1557', 'Zurückzuzahlende Vorsteuer §15a UStG,bewegl.WG');
INSERT INTO gifi (accno,description) VALUES ('1558', 'Nachträgl.abziehb.Vorst.§15aUStG,unbewegl.WG');
INSERT INTO gifi (accno,description) VALUES ('1559', 'Zurückzuzahlende Vorst.§15aUStG,unbewegl.WG');
INSERT INTO gifi (accno,description) VALUES ('1560', 'Aufzuteilende Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('1561', 'Aufzuteilende Vorsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('1562', 'Aufzuteilende Vorst.a.innergem.Erwerb');
INSERT INTO gifi (accno,description) VALUES ('1565', 'Aufzuteilende Vorsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('1567', 'Aufzuteilende Vorst.n.§13b UStG');
INSERT INTO gifi (accno,description) VALUES ('1568', 'Aufzuteilende Vorst.n.§13b UStG 16%');
INSERT INTO gifi (accno,description) VALUES ('1570', 'Abziehbare Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('1571', 'Abziebare Vorsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('1572', 'Abziehb. VorSt innergemein. Erwerb');
INSERT INTO gifi (accno,description) VALUES ('1573', 'Abziehb.VorSt. innergem.Erwerb 16%');
INSERT INTO gifi (accno,description) VALUES ('1575', 'Abziehbare Vorsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('1577', 'Vorst.n.allgem.Durchschnittssätzen UStVA Kz.63');
INSERT INTO gifi (accno,description) VALUES ('1578', 'Abziehb.VorSt. n. §13b UStG');
INSERT INTO gifi (accno,description) VALUES ('1579', 'Abziehb.VorSt. n.§13b UStG 16%');
INSERT INTO gifi (accno,description) VALUES ('1580', 'Gegenkonto Vorsteuer §4/3 EStG');
INSERT INTO gifi (accno,description) VALUES ('1581', 'Auflösung Vorst.a.Vorjahr §4/3 EStG');
INSERT INTO gifi (accno,description) VALUES ('1584', 'abziehb.VorSt IG Erwerb Neufzg.b.Lief. o. USt.Ident.Nr');
INSERT INTO gifi (accno,description) VALUES ('1588', 'Bezahlte Einfuhrumsatzsteuer');
INSERT INTO gifi (accno,description) VALUES ('1590', 'Durchlaufende Posten');
INSERT INTO gifi (accno,description) VALUES ('1592', 'Fremdgeld');
INSERT INTO gifi (accno,description) VALUES ('1593', 'Verrechnungskto.erh.Anz.bei Buchung über Debitorenkto.');
INSERT INTO gifi (accno,description) VALUES ('1594', 'Forderungen geg. verb. Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('1595', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1596', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1597', 'Ford.geg.Untern.m.Beteiligungsverh.');
INSERT INTO gifi (accno,description) VALUES ('1598', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1599', '- Restlaufzeit grösser als 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1600', 'Verbindlichkeiten aus Lief.u.Leist.');
INSERT INTO gifi (accno,description) VALUES ('1601', 'Verbindlichkeiten a.Lief.und Leist.');
INSERT INTO gifi (accno,description) VALUES ('1610', 'Vblk.a.Lief.u.Leist.ohne Kontokorrent');
INSERT INTO gifi (accno,description) VALUES ('1624', 'Vblk.a.Lief.u.Leist.f.Investitionen f.§4/3 EStG');
INSERT INTO gifi (accno,description) VALUES ('1625', 'Vblk.a.Lief.u.Leist.o.Kontokorrent RLZ b.1Jahr');
INSERT INTO gifi (accno,description) VALUES ('1626', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1628', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1630', 'Verbindl.Lief.u.Leist.gegü.verb.Unt');
INSERT INTO gifi (accno,description) VALUES ('1631', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1635', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1638', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1640', 'Verb.L.u.L gegü.Unter.m.Beteiligungsv');
INSERT INTO gifi (accno,description) VALUES ('1641', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1645', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1648', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1650', 'Verb.L.u.L gegü.Gesellschaftern');
INSERT INTO gifi (accno,description) VALUES ('1651', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1655', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1658', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1659', 'Gegenkto. 1625-1658 b.Aufteilung Kreditorenkonto');
INSERT INTO gifi (accno,description) VALUES ('1660', 'Schuldwechsel');
INSERT INTO gifi (accno,description) VALUES ('1661', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1680', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1690', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1700', 'Sonstige Verbindlichkeiten');
INSERT INTO gifi (accno,description) VALUES ('1701', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1702', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1703', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1704', 'Sonst.Vblk.z.B.n.§11(2)S.2EStGf.§4/3EStG');
INSERT INTO gifi (accno,description) VALUES ('1705', 'Darlehen');
INSERT INTO gifi (accno,description) VALUES ('1706', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1707', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1708', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1709', 'Gewinnverfügungskonto stiller Ges.');
INSERT INTO gifi (accno,description) VALUES ('1710', 'Erhaltene Anzahlungen-Verbindlichke');
INSERT INTO gifi (accno,description) VALUES ('1711', 'Erhaltene,versteuerte Anzahlungen 7% (Vblk)');
INSERT INTO gifi (accno,description) VALUES ('1716', 'Erhaltene verst.Anzahlungen 15% USt(Vblk.)');
INSERT INTO gifi (accno,description) VALUES ('1717', 'Erhaltene,versteuerte Anzahl. 16%(Vblk)');
INSERT INTO gifi (accno,description) VALUES ('1719', 'Erhaltene Anzahlungen bis 1j.');
INSERT INTO gifi (accno,description) VALUES ('1720', '- Restlaufzeit 1 b.5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1721', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1722', 'Erhaltene Anzahlung v.Vorräten offen abgesetzt');
INSERT INTO gifi (accno,description) VALUES ('1730', 'Kreditkartenabrechnung');
INSERT INTO gifi (accno,description) VALUES ('1731', 'Agenturwarenabrechnung');
INSERT INTO gifi (accno,description) VALUES ('1732', 'Erhaltene Kautionen');
INSERT INTO gifi (accno,description) VALUES ('1733', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1734', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1735', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1736', 'Vblk.a.Betriebssteuern u.-abgaben');
INSERT INTO gifi (accno,description) VALUES ('1737', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1738', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1739', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1740', 'Vblk.aus Lohn-u.Gehalt');
INSERT INTO gifi (accno,description) VALUES ('1741', 'Verbindl.a.Lohn-und Kirchensteuer');
INSERT INTO gifi (accno,description) VALUES ('1742', 'Vblk.i.Rahmen d.sozialen Sicherheit');
INSERT INTO gifi (accno,description) VALUES ('1743', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1744', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1745', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1746', 'Vblk.aus Einbehaltungen (KapESt)');
INSERT INTO gifi (accno,description) VALUES ('1747', 'Vblk.f.Verbrauchsteuern');
INSERT INTO gifi (accno,description) VALUES ('1748', 'Vblk.f.Einbehaltungen v.Arbeitnehmern');
INSERT INTO gifi (accno,description) VALUES ('1749', 'Vblk.a.das Finanzamt a.abzuführendem Bauabzugsbetrag');
INSERT INTO gifi (accno,description) VALUES ('1750', 'Vblk.a.Vermögensbildung');
INSERT INTO gifi (accno,description) VALUES ('1751', '- Restlaufzeit bis 1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('1752', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1753', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('1754', 'Steuerzahlungen an andere EG-Länder');
INSERT INTO gifi (accno,description) VALUES ('1755', 'Lohn-und Gehaltsverrechnung');
INSERT INTO gifi (accno,description) VALUES ('1758', 'USt-Abzugsverfahren 16% od.USt.n.§13bUStG');
INSERT INTO gifi (accno,description) VALUES ('1760', 'Umsatzsteuer nicht fällig');
INSERT INTO gifi (accno,description) VALUES ('1761', 'Umsatzsteuer nicht fällig 7%');
INSERT INTO gifi (accno,description) VALUES ('1762', 'Umsatzsteuer nicht fällig a.im Inland stpfl.EG Lief.');
INSERT INTO gifi (accno,description) VALUES ('1763', 'Umsatzsteuer nicht fällig a.i.Inland stpfl.EG-Lief.16%');
INSERT INTO gifi (accno,description) VALUES ('1765', 'Umsatzsteuer n.fällig 16%');
INSERT INTO gifi (accno,description) VALUES ('1767', 'Umsatzsteuer a.i.anderen EG-Land stpfl.Lieferungen');
INSERT INTO gifi (accno,description) VALUES ('1768', 'Umsatzsteuer a.i.and.EG-Land stpfl.sonst.Leist./Werklief.');
INSERT INTO gifi (accno,description) VALUES ('1770', 'Umsatzsteuer');
INSERT INTO gifi (accno,description) VALUES ('1771', 'Umsatzsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('1772', 'Umsatzsteuer aus innergem. Erwerb');
INSERT INTO gifi (accno,description) VALUES ('1773', 'Umsatzsteuer innergem.Erwerb 16%');
INSERT INTO gifi (accno,description) VALUES ('1775', 'Umsatzsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('1777', 'Ust aus im Inland stpfl. EG-Lief16%');
INSERT INTO gifi (accno,description) VALUES ('1779', 'Umsatzsteuer a.innergem.Erwerb ohne Vorsteuerabzug');
INSERT INTO gifi (accno,description) VALUES ('1780', 'Umsatzsteuer-Vorauszahlungen');
INSERT INTO gifi (accno,description) VALUES ('1781', 'Umsatzsteuer-Vorauszahlung 1/11');
INSERT INTO gifi (accno,description) VALUES ('1782', 'Nachsteuer, UStVA Kz.65');
INSERT INTO gifi (accno,description) VALUES ('1783', 'In Rechn unberecht.ausgew.geschuld.Steuerbetr.UStVAKz69');
INSERT INTO gifi (accno,description) VALUES ('1784', 'Ust IG Erwerb Neufahrzeug o.Ust ID');
INSERT INTO gifi (accno,description) VALUES ('1785', 'Umsatzsteuer n.§13b UStG');
INSERT INTO gifi (accno,description) VALUES ('1786', 'Umsatzsteuer n.§13b UStG 16%');
INSERT INTO gifi (accno,description) VALUES ('1788', 'Einfuhrumsatzsteuer augeschoben bis');
INSERT INTO gifi (accno,description) VALUES ('1789', 'Umsatzsteuer laufendes Jahr');
INSERT INTO gifi (accno,description) VALUES ('1790', 'Umsatzsteuer Vorjahr');
INSERT INTO gifi (accno,description) VALUES ('1791', 'Umsatzsteuer frühere Jahre');
INSERT INTO gifi (accno,description) VALUES ('1792', 'Sonstige Verrechnungskonten');
INSERT INTO gifi (accno,description) VALUES ('1793', 'Verrechnungskto.geleist.Anz.b.Buchung über Kreditorenkto.');
INSERT INTO gifi (accno,description) VALUES ('1800', 'Privatentnahme allgemein');
INSERT INTO gifi (accno,description) VALUES ('1810', 'Privatsteuern');
INSERT INTO gifi (accno,description) VALUES ('1820', 'Sonderausgaben beschränkt abzugsfähig');
INSERT INTO gifi (accno,description) VALUES ('1830', 'Sonderausgaben unbeschr.anzugsfähig');
INSERT INTO gifi (accno,description) VALUES ('1840', 'Zuwendungen, Spenden');
INSERT INTO gifi (accno,description) VALUES ('1850', 'Aussergewöhnl.Belastungen');
INSERT INTO gifi (accno,description) VALUES ('1860', 'Grundstücksaufwand');
INSERT INTO gifi (accno,description) VALUES ('1870', 'Grundstücksertrag');
INSERT INTO gifi (accno,description) VALUES ('1880', 'Unentgeltliche Wertabgaben');
INSERT INTO gifi (accno,description) VALUES ('1890', 'Privateinlagen');
INSERT INTO gifi (accno,description) VALUES ('1900', 'Privatentnahmen allgemein');
INSERT INTO gifi (accno,description) VALUES ('1910', 'Privatsteuern');
INSERT INTO gifi (accno,description) VALUES ('1920', 'Sonderausgaben beschränkt abzugsfähig');
INSERT INTO gifi (accno,description) VALUES ('1930', 'Sonderausgaben unbeschr.anzugsfähig');
INSERT INTO gifi (accno,description) VALUES ('1940', 'Zuwendungen, Spenden');
INSERT INTO gifi (accno,description) VALUES ('1950', 'Aussergewöhnl.Belastungen');
INSERT INTO gifi (accno,description) VALUES ('1960', 'Grundstücksaufwand');
INSERT INTO gifi (accno,description) VALUES ('1970', 'Grundstücksertrag');
INSERT INTO gifi (accno,description) VALUES ('1980', 'Unentgeltliche Wertabgaben');
INSERT INTO gifi (accno,description) VALUES ('1990', 'Privateinlagen');
INSERT INTO gifi (accno,description) VALUES ('2000', 'Außerordentliche Aufwendung');
INSERT INTO gifi (accno,description) VALUES ('2001', 'Außerordentl.Aufwendungen finanzwirksam');
INSERT INTO gifi (accno,description) VALUES ('2005', 'Außerordentl.Aufwendungen nicht finanzwirksam');
INSERT INTO gifi (accno,description) VALUES ('2010', 'Betriebsfremde Aufwendungen soweit n.außerord.');
INSERT INTO gifi (accno,description) VALUES ('2020', 'Periodenfremde Aufwend.(soweit n.außerordentlich');
INSERT INTO gifi (accno,description) VALUES ('2100', 'Zinsen und ähnl.Aufwendungen');
INSERT INTO gifi (accno,description) VALUES ('2103', 'Steuerl.abzugsfähig,and.Nebenl.zu Steuern');
INSERT INTO gifi (accno,description) VALUES ('2104', 'Steuerl.nicht.abzugsf.ande.Nl.z.Ste');
INSERT INTO gifi (accno,description) VALUES ('2107', 'Zinsaufwendung-betriebliche Steuern §223aAO');
INSERT INTO gifi (accno,description) VALUES ('2108', 'Zinsaufwendung-Personensteuer');
INSERT INTO gifi (accno,description) VALUES ('2109', 'Zinsaufwendungen an verb.Unternehm.');
INSERT INTO gifi (accno,description) VALUES ('2110', 'Zinsaufwendung f.kurzf.Verbindlichk');
INSERT INTO gifi (accno,description) VALUES ('2115', 'Zinsen u.ähnl.Aufwendungen 100%/50% n.abzugsf.(inländ.Kap.Ges)');
INSERT INTO gifi (accno,description) VALUES ('2116', 'Zinsen u.ähnl.Aufwend.a.verb.Untern.100%/50% n.abzugsf.(inl.Kap.Ges)');
INSERT INTO gifi (accno,description) VALUES ('2118', 'In Dauerschuldzinsen umqualifizierte Zinsen a.kurzf.Vblk.');
INSERT INTO gifi (accno,description) VALUES ('2119', 'Zinsaufwend.f.kurzfr.Vblk.an verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('2120', 'Zinsaufwendung f.langf.Verbindlichk');
INSERT INTO gifi (accno,description) VALUES ('2126', 'Zinsen zur Finanzierung des Anlagevermögens');
INSERT INTO gifi (accno,description) VALUES ('2127', 'Renten u.dauernde Lasten a.Gründung/Erwerb §8GewStG');
INSERT INTO gifi (accno,description) VALUES ('2128', 'Zinsaufwend.an Mituntern.f.d.Hingabe v.langfr.Kapital §15EStG');
INSERT INTO gifi (accno,description) VALUES ('2129', 'Zinsaufwend.f.langfr.Vblk.an verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('2130', 'Diskontaufwendung');
INSERT INTO gifi (accno,description) VALUES ('2139', 'Diskontaufwendungen an verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('2140', 'Zinsähnliche Aufwendungen');
INSERT INTO gifi (accno,description) VALUES ('2149', 'Zinsähnl.Aufwendungen an verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('2150', 'Aufwendungen aus Kursdifferenzen');
INSERT INTO gifi (accno,description) VALUES ('2165', 'Aufw.a.d.Währungsumstell.a.d.Euro');
INSERT INTO gifi (accno,description) VALUES ('2166', 'Aufwendungen a.Bewertung Finanzmittelfonds');
INSERT INTO gifi (accno,description) VALUES ('2170', 'Nicht abziehbare Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('2171', 'Nicht abziehbare Vorsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('2175', 'Nicht abziehbare Vorsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('2200', 'Körperschaftssteuer');
INSERT INTO gifi (accno,description) VALUES ('2203', 'Körperschaftssteuer für Vorjahr');
INSERT INTO gifi (accno,description) VALUES ('2205', 'Anrechb.Körperschaftsst.auf vereinn.Kapitalertr.');
INSERT INTO gifi (accno,description) VALUES ('2208', 'Solidaritätszuschlag');
INSERT INTO gifi (accno,description) VALUES ('2209', 'Solidaritätszuschlag für Vorjahr');
INSERT INTO gifi (accno,description) VALUES ('2210', 'Kapitalertragssteuer 25%');
INSERT INTO gifi (accno,description) VALUES ('2213', 'Anrechb.Solidaritätszusch.Kapitalertragsst.25%');
INSERT INTO gifi (accno,description) VALUES ('2214', 'Anrechenb.Soli auf Kapitalertragssteuer 20%');
INSERT INTO gifi (accno,description) VALUES ('2215', 'Zinsabschlagsteuer');
INSERT INTO gifi (accno,description) VALUES ('2218', 'Anrechb.Solidari.zuschlag a.Zinsabschlagst.');
INSERT INTO gifi (accno,description) VALUES ('2223', 'Vermögensteuer für Vorjahre');
INSERT INTO gifi (accno,description) VALUES ('2280', 'Stnachzahl.Vorj.v.Einkomm u.Ertrag');
INSERT INTO gifi (accno,description) VALUES ('2282', 'Sterstat.Vorj.Steuer v.Eink.u.Ertrag');
INSERT INTO gifi (accno,description) VALUES ('2284', 'Ertr.a.d.Aufl.v.Rücks.f.St.v.Ein.Er');
INSERT INTO gifi (accno,description) VALUES ('2285', 'Steuernachzahlung Vorj.f.sons.Steue');
INSERT INTO gifi (accno,description) VALUES ('2287', 'Steuererstattung Vorj.f.sons.Steuer');
INSERT INTO gifi (accno,description) VALUES ('2289', 'Erträge a.d.Aufl.v. Rück.f.sons.Ste');
INSERT INTO gifi (accno,description) VALUES ('2300', 'Sonstige Aufwendungen');
INSERT INTO gifi (accno,description) VALUES ('2307', 'Sonst.Aufwend.betriebsfremd u.regelmässig');
INSERT INTO gifi (accno,description) VALUES ('2309', 'Sonst.Aufwend. unregelmäßig');
INSERT INTO gifi (accno,description) VALUES ('2310', 'Anlagenabgänge Sachanlagen Restbuchw.b.Buchverlust');
INSERT INTO gifi (accno,description) VALUES ('2311', 'Anlagenabgänge immat.VG (Restbuchw.b.Buchverlust');
INSERT INTO gifi (accno,description) VALUES ('2312', 'Anlagenabgänge Finanzanlagen (Restbuchw.b.Buchverlust');
INSERT INTO gifi (accno,description) VALUES ('2313', 'Anlagenabgänge Finanzanl.100%/50% n.abzugsf.(Restbuchw.b.Buchverlust');
INSERT INTO gifi (accno,description) VALUES ('2315', 'Anlagenabgänge Sachanlagen Restbuchw.b.Buchgewinn');
INSERT INTO gifi (accno,description) VALUES ('2316', 'Anlagenabgänge immat.VG (Restbuchwert b.Buchgewinn');
INSERT INTO gifi (accno,description) VALUES ('2317', 'Anlagenabgänge Finanzanlagen (Restbuchwert b.Buchgewinn');
INSERT INTO gifi (accno,description) VALUES ('2318', 'Anlagenabgänge Finanzanlagen 100%/50% steuerfr.(Restbuchw.b.Buchgewinn');
INSERT INTO gifi (accno,description) VALUES ('2320', 'Verluste Abgang Gegenst.d.Anlagever');
INSERT INTO gifi (accno,description) VALUES ('2323', 'Verluste a.d.Veräußerung v.Anteilen a.Kapitalges.100%/50% n.abzugsf.');
INSERT INTO gifi (accno,description) VALUES ('2325', 'Verlust a.d.Abg.v.Gegens.d.Umlaufve');
INSERT INTO gifi (accno,description) VALUES ('2340', 'Einstellungen Sopo m.Rückanlageant.steuerfrei');
INSERT INTO gifi (accno,description) VALUES ('2341', 'Einstellungen in SoPo m.Rücklageanteil (Ansparabschreibung');
INSERT INTO gifi (accno,description) VALUES ('2345', 'Einstellungen Sopo m.R.(Sonderafa)');
INSERT INTO gifi (accno,description) VALUES ('2346', 'Einst.in SoPo m.Rücklageanteil (§52 Abs.16 EStG');
INSERT INTO gifi (accno,description) VALUES ('2347', 'Einst.in SoPo m.Rücklageanteil (aus der Währungsumst.EUR)');
INSERT INTO gifi (accno,description) VALUES ('2348', 'Aufwend.a.d.Zuschreibung v.steuerlich niedriger bewert.Vblk.');
INSERT INTO gifi (accno,description) VALUES ('2349', 'Aufwend.a.d.Zuschreibung v.steuerlich niedriger bewert.Rückst.');
INSERT INTO gifi (accno,description) VALUES ('2350', 'Grundstücksaufwendungen');
INSERT INTO gifi (accno,description) VALUES ('2375', 'Grundsteuer');
INSERT INTO gifi (accno,description) VALUES ('2380', 'Zuwend.,Spenden,steuerlich n.abziehbar');
INSERT INTO gifi (accno,description) VALUES ('2381', 'Zuwend.,Spenden f.wissenschaftl.u.kulturelle Zwecke');
INSERT INTO gifi (accno,description) VALUES ('2382', 'Zuwend.,Spenden f.mildtätige Zwecke');
INSERT INTO gifi (accno,description) VALUES ('2383', 'Zuwend.,Spenden f.kirchliche,religiöse u.gemeinnützige Zwecke');
INSERT INTO gifi (accno,description) VALUES ('2384', 'Zuwend.,Spenden an politische Parteien');
INSERT INTO gifi (accno,description) VALUES ('2385', 'Nicht abziehb.Hälfte der Aufsichtsratsvergütungen');
INSERT INTO gifi (accno,description) VALUES ('2386', 'Abziehb.Aufsichtsratsvergütungen');
INSERT INTO gifi (accno,description) VALUES ('2387', 'Zuwend.,Spenden an Stiftungen f.gemeinnützige Zwecke i.S.d.§52(2)Nr.1-3AO');
INSERT INTO gifi (accno,description) VALUES ('2388', 'Zuwend.,Spenden an Stiftungen f.gemeinnützige Zwecke i.S.d.§52(2)Nr.4AO');
INSERT INTO gifi (accno,description) VALUES ('2389', 'Zuwend.,Spenden an Stiftungen f.kirchl.,religöse u.gemeinnützige Zwecke');
INSERT INTO gifi (accno,description) VALUES ('2390', 'Zuwend.,Spenden an Stiftungen f.wissenschaftl.,mildtätige,kulturelle Zwecke');
INSERT INTO gifi (accno,description) VALUES ('2400', 'Forderungsverlust-übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('2401', 'Forderungsverluste 7% USt.(übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('2402', 'Forderungsverluste a.steuerfreien EG-Lief.(übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('2403', 'Forderungsverluste a.im Inland steuerpfl.EG-Lieferungen 7% USt.(übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('2404', 'Forderungsverluste a.im Inland steuerpfl.EG-Lief.16% USt.(übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('2405', 'Forderungsverluste 16% USt.(übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('2430', 'Forderungsverluste-unüblich  hoch');
INSERT INTO gifi (accno,description) VALUES ('2450', 'Einstell.i.d.Pauschalwertbe.z.Forde');
INSERT INTO gifi (accno,description) VALUES ('2451', 'Einstell.i.d.Einzelwertb.z.Forderun');
INSERT INTO gifi (accno,description) VALUES ('2490', 'Aufwendung aus Verlustübernahme');
INSERT INTO gifi (accno,description) VALUES ('2492', 'Abgef.Gewinn aufgr.e.Gewinngemeinsc');
INSERT INTO gifi (accno,description) VALUES ('2493', 'Abgef.Gewinnant.an stille Gesellsch §8GewsT');
INSERT INTO gifi (accno,description) VALUES ('2494', 'Abgeführte Gewinne auf Grund eines Gewinn-od.Teilgewinnabführungsvertrages');
INSERT INTO gifi (accno,description) VALUES ('2495', 'Einst.Kapitalrückl.n.Vorschr.über d.vereinf.Kapitalherabsetzung');
INSERT INTO gifi (accno,description) VALUES ('2496', 'Einstellungen in die gesetzl.Rückla');
INSERT INTO gifi (accno,description) VALUES ('2497', 'Einstellungen in satzungsmässige Rücklagen');
INSERT INTO gifi (accno,description) VALUES ('2498', 'Einstellunen in die Rücklage für eigene Anteile');
INSERT INTO gifi (accno,description) VALUES ('2499', 'Einstellungen in andere Gewinnrücklagen');
INSERT INTO gifi (accno,description) VALUES ('2500', 'Außerordentliche Erträge');
INSERT INTO gifi (accno,description) VALUES ('2501', 'Außerordentliche Erträge finanzwirksam');
INSERT INTO gifi (accno,description) VALUES ('2505', 'Außerordentliche Erträge nicht finanzwirksam');
INSERT INTO gifi (accno,description) VALUES ('2510', 'Betriebsfremde Erträge nichtaußerorden');
INSERT INTO gifi (accno,description) VALUES ('2520', 'Periodenfremde Erträge nicht außero');
INSERT INTO gifi (accno,description) VALUES ('2600', 'Erträge aus Beteiligungen');
INSERT INTO gifi (accno,description) VALUES ('2615', 'Lfd.Erträge a.Anteilen an Kap.Ges.(Bet.100%/50% steuerfrei(inländ.Kap.Ges)');
INSERT INTO gifi (accno,description) VALUES ('2616', 'Lfd.Erträge a.Ant.a.Kap.Ges.(verb.Untern)100%/50% steuerfr.(inländ.Kap.Ges)');
INSERT INTO gifi (accno,description) VALUES ('2617', 'Gewinn aus Anteilen an nicht steuerpfl.inländ.Kapitalges.§92aGewS.');
INSERT INTO gifi (accno,description) VALUES ('2618', 'Gewinnanteile aus Mitunternehmerschaft §9 GewStG');
INSERT INTO gifi (accno,description) VALUES ('2619', 'Erträge a.Beteil.a.verb.Untérnehmer');
INSERT INTO gifi (accno,description) VALUES ('2620', 'Erträge a.anderen Wertp u.Ausleihungen d.FinanzAV');
INSERT INTO gifi (accno,description) VALUES ('2625', 'Lfd.Erträge a.Anteilen a.Kap.Ges.(FinanzAV)100%/50% steuerfr.(inländ.Kap.Ges)');
INSERT INTO gifi (accno,description) VALUES ('2626', 'Lfd.Erträge a.Anteilen a.Kap.Ges.(verb.Untern)100%/50% steuerfr.(inländ.Kap.Ges)');
INSERT INTO gifi (accno,description) VALUES ('2649', 'Erträge a.and.Wertpapieren u.Ausleih.des FinanzAV a.verbund.Untern.');
INSERT INTO gifi (accno,description) VALUES ('2650', 'Sonstige Zinsen und ähnliche Erträge');
INSERT INTO gifi (accno,description) VALUES ('2655', 'Lfd.Erträge a.Anteilen a.Kap.Ges.(UV)100%/50% steuerfr.(inländ.Kap.Ges)');
INSERT INTO gifi (accno,description) VALUES ('2656', 'Lfd.Erträge a.Anteilen a.Kap.Ges.(verb.Untern.)100%/50% steuerfr.(inländ.Kap.Ges)');
INSERT INTO gifi (accno,description) VALUES ('2657', 'Zinserträge-betriebliche Steuern');
INSERT INTO gifi (accno,description) VALUES ('2658', 'Zinserträge-Körperschaftssteuer Vermögensst.');
INSERT INTO gifi (accno,description) VALUES ('2659', 'Sons.Zinsen u.ähl.Ertr.a.verb.Unter');
INSERT INTO gifi (accno,description) VALUES ('2660', 'Erträge aus Kursdifferenzen');
INSERT INTO gifi (accno,description) VALUES ('2665', 'Erträge a.d.Währungumst.a.d. Euro');
INSERT INTO gifi (accno,description) VALUES ('2666', 'Erträge a.Bewertung Finanzmittelfonds');
INSERT INTO gifi (accno,description) VALUES ('2670', 'Diskonterträge');
INSERT INTO gifi (accno,description) VALUES ('2679', 'Diskonterträge a.verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('2680', 'Zinsähnliche Erträge');
INSERT INTO gifi (accno,description) VALUES ('2689', 'Zinsähnliche Erträge aus verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('2700', 'Sonstige Erträge');
INSERT INTO gifi (accno,description) VALUES ('2705', 'Sons.Erträge betrieb. u. regelmäßig');
INSERT INTO gifi (accno,description) VALUES ('2707', 'Sonst.Erträge betriebsfremd u.regelmäßig');
INSERT INTO gifi (accno,description) VALUES ('2709', 'Sonst.Erträge unregelmäßig');
INSERT INTO gifi (accno,description) VALUES ('2710', 'Ertrag a.d.Zuschreib.d.Anlagevermög');
INSERT INTO gifi (accno,description) VALUES ('2711', 'Erträge aus Zuschreibungen des immat.Anlagevermögens');
INSERT INTO gifi (accno,description) VALUES ('2712', 'Erträge aus Zuschreibungen des Finanzanlagevermögens');
INSERT INTO gifi (accno,description) VALUES ('2713', 'Erträge aus Zuschreib. d.Finanzanlagevermögens 100%/50% steuerfrei');
INSERT INTO gifi (accno,description) VALUES ('2714', 'Erträge aus Zuschreib. d.and.Anlagevermögens 100%/50% steuerfrei');
INSERT INTO gifi (accno,description) VALUES ('2715', 'Ertr.a.Zuschreib.d.Umlaufvermögens');
INSERT INTO gifi (accno,description) VALUES ('2716', 'Erträge aus Zuschreib.d.Umlaufvermögens 100%/50% steuerfrei');
INSERT INTO gifi (accno,description) VALUES ('2720', 'Ertr.a.d.Abgang v.Gegens.d.Anlageve');
INSERT INTO gifi (accno,description) VALUES ('2723', 'Erträge aus der Veräußerung v.Anteilen an Kap.Ges.100%/50% steuerfrei');
INSERT INTO gifi (accno,description) VALUES ('2725', 'Ertr.a.d.Abg.v.Gegenst.d.Umlaufverm');
INSERT INTO gifi (accno,description) VALUES ('2730', 'Ertr.a.Herabsetzung d.PWB zu Forderungen');
INSERT INTO gifi (accno,description) VALUES ('2731', 'Ertr.a.Herab.d.Einzelw.z.Forderunge');
INSERT INTO gifi (accno,description) VALUES ('2732', 'Ertr. aus abgeschriebenen Forderung');
INSERT INTO gifi (accno,description) VALUES ('2734', 'Erträge aus der steuerlich niedrigeren Bewertung v.Vblk.');
INSERT INTO gifi (accno,description) VALUES ('2735', 'Ertr.a.d.Auflösung v.Rückstellungen');
INSERT INTO gifi (accno,description) VALUES ('2736', 'Ertr.a.d.steuerl.niedrig.Bewertung v.Rückst.');
INSERT INTO gifi (accno,description) VALUES ('2737', 'Ertr.a.d..Aufl.v.Sonderp.m.Rücklage (a.Währungsumst.EUR');
INSERT INTO gifi (accno,description) VALUES ('2738', 'Ertr.a.d.Aufl.v.Sopo.m.Rücklageant.');
INSERT INTO gifi (accno,description) VALUES ('2739', 'Erträge Aufl. Sopo m.R.(Ansparafa)');
INSERT INTO gifi (accno,description) VALUES ('2740', 'Erträge Auflösung Sopo (stfreie Rü)m.Rücklageanteil');
INSERT INTO gifi (accno,description) VALUES ('2741', 'Ertr.a.d.Aufl.v.Sonderp.m.Rücklagen Sonderafa');
INSERT INTO gifi (accno,description) VALUES ('2742', 'Versicherungsentschädigungen');
INSERT INTO gifi (accno,description) VALUES ('2743', 'Investitionszuschüsse-steuerpflicht');
INSERT INTO gifi (accno,description) VALUES ('2744', 'Investitionszulage-steuerfrei');
INSERT INTO gifi (accno,description) VALUES ('2745', 'Erträge aus Kapitalherabsetzung');
INSERT INTO gifi (accno,description) VALUES ('2750', 'Grundstückserträge');
INSERT INTO gifi (accno,description) VALUES ('2790', 'Erträge aus Verlustübernahme');
INSERT INTO gifi (accno,description) VALUES ('2792', 'Erhalt.Gewinne aufgr.e.Gewinngemein');
INSERT INTO gifi (accno,description) VALUES ('2794', 'Erhalt.Gewinn aufgr.e.GAV-TeilGAV e.Gewinn-od.Teilgew.abf.vertr.');
INSERT INTO gifi (accno,description) VALUES ('2795', 'Entnahme aus der Kapitalrücklage');
INSERT INTO gifi (accno,description) VALUES ('2796', 'Entnahme a.d. gesetzlichen Rücklage');
INSERT INTO gifi (accno,description) VALUES ('2798', 'Entnahmen aus der Rücklage für eigene Anteile');
INSERT INTO gifi (accno,description) VALUES ('2799', 'Entnahmen aus anderen Gewinnrücklagen');
INSERT INTO gifi (accno,description) VALUES ('2860', 'Gewinnvortrag nach Verwendung');
INSERT INTO gifi (accno,description) VALUES ('2862', 'Gewinnvortrag 40% Vorbelastung');
INSERT INTO gifi (accno,description) VALUES ('2864', 'Gewinnvortrag 0% Vorbelastung (steuerl.Einlagekonto');
INSERT INTO gifi (accno,description) VALUES ('2866', 'Gewinnvortrag 0% Vorbelastung (EK02)');
INSERT INTO gifi (accno,description) VALUES ('2868', 'Verlustvortrag nach Verwendung');
INSERT INTO gifi (accno,description) VALUES ('2869', 'Vortrag auf neue Rechnungen (GuV');
INSERT INTO gifi (accno,description) VALUES ('2870', 'Vorabausschüttung');
INSERT INTO gifi (accno,description) VALUES ('2890', 'Verrechneter kalk.Unternehmerlohn');
INSERT INTO gifi (accno,description) VALUES ('2891', 'Verrechneter kalk.Miete und Pacht');
INSERT INTO gifi (accno,description) VALUES ('2892', 'Verrechnete kalkulatorische Zinsen');
INSERT INTO gifi (accno,description) VALUES ('2893', 'Verrechnete kalkulatorische AfA');
INSERT INTO gifi (accno,description) VALUES ('2894', 'Verrechnete kalk.Wagnisse');
INSERT INTO gifi (accno,description) VALUES ('2895', 'Verrechneter kalk.Lohn f.unentgeltl.Mitarbeiter');
INSERT INTO gifi (accno,description) VALUES ('2990', 'Aufwendung/Erträge Umrechnungsdiff');
INSERT INTO gifi (accno,description) VALUES ('3000', 'Roh,-Hilfs,-und Betriebsstoffe');
INSERT INTO gifi (accno,description) VALUES ('3090', 'Energiestoffe (Fertigung)');
INSERT INTO gifi (accno,description) VALUES ('3100', 'Fremdleistungen');
INSERT INTO gifi (accno,description) VALUES ('3110', 'Leist.v.ausländ.Untern. 7% VSt.u.7%USt.');
INSERT INTO gifi (accno,description) VALUES ('3120', 'Leist.v.ausländ.Untern. 16% VSt.u.16%USt.');
INSERT INTO gifi (accno,description) VALUES ('3130', 'Leist.v.ausländ.Untern.ohne Vorst.u.7%USt.');
INSERT INTO gifi (accno,description) VALUES ('3140', 'Leist.v.ausländ.Untern.o.Vorst.u.16% USt.');
INSERT INTO gifi (accno,description) VALUES ('3150', 'Leist.v.ausländ.Untern.(0-Regelung)');
INSERT INTO gifi (accno,description) VALUES ('3200', 'Wareneingang');
INSERT INTO gifi (accno,description) VALUES ('3300', 'Wareneingang 7% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3400', 'Wareneingang 16% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3420', 'Innergemein.Erwerb 7% VorSt u. Ust');
INSERT INTO gifi (accno,description) VALUES ('3425', 'Innergem.Erwerb 16% VorSt u. Ust');
INSERT INTO gifi (accno,description) VALUES ('3430', 'Innergem.Erwerb o.VSt.u.7% USt.');
INSERT INTO gifi (accno,description) VALUES ('3435', 'Innergem.Erwerb o.VSt.u.16% USt.');
INSERT INTO gifi (accno,description) VALUES ('3440', 'Innergem.Erwerb v.Neufahrz.v.Lief.o.USt.Identnr.16%VSt.u.16%USt.');
INSERT INTO gifi (accno,description) VALUES ('3500', 'Wareneingang 5% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3505', 'Wareneingang 6% Vosteuer');
INSERT INTO gifi (accno,description) VALUES ('3530', 'Wareneingang 9% Vosteuer');
INSERT INTO gifi (accno,description) VALUES ('3535', 'Wareneingang 10% Vosteuer');
INSERT INTO gifi (accno,description) VALUES ('3540', 'Wareneingang 9% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3550', 'Steuerfreier innergem.Erwerb');
INSERT INTO gifi (accno,description) VALUES ('3600', 'Nicht abziehbare Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3610', 'Nicht abziehb.Vorsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('3650', 'Nicht abziehb.Vorsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('3700', 'Nachlässe');
INSERT INTO gifi (accno,description) VALUES ('3710', 'Nachlässe 7% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3720', 'Nachlässe 16% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3723', 'Nachlässe 15% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3724', 'Nachlässe a.innergem.Erwerb 7% VSt.u.7%USt.');
INSERT INTO gifi (accno,description) VALUES ('3725', 'Nachlässe a.innergem.Erwerb 16% VSt.u.16%USt.');
INSERT INTO gifi (accno,description) VALUES ('3727', 'Nachlässe a.innergem.Erwerb 15% VSt.u.15%USt.');
INSERT INTO gifi (accno,description) VALUES ('3730', 'Erhaltene Skonti');
INSERT INTO gifi (accno,description) VALUES ('3731', 'Erhaltene Skonti 7% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3735', 'Erhaltene Skonti 16% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3740', 'Erhaltene Boni');
INSERT INTO gifi (accno,description) VALUES ('3750', 'Erhaltene Boni 7% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3760', 'Erhaltene Boni 16% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3770', 'Erhaltene Rabatte');
INSERT INTO gifi (accno,description) VALUES ('3780', 'Erhaltene Rabatte 7% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3790', 'Erhaltene Rabatte 16% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('3800', 'Bezugsnebenkosten');
INSERT INTO gifi (accno,description) VALUES ('3830', 'Leergut');
INSERT INTO gifi (accno,description) VALUES ('3850', 'Zölle und Einfuhrabgaben');
INSERT INTO gifi (accno,description) VALUES ('3960', 'Bestandsver.Roh-,Hilfs-.Betriebs.sow.bez.Waren');
INSERT INTO gifi (accno,description) VALUES ('3970', 'Bestand Roh-,Hilfs-,u.Betriebsstoff');
INSERT INTO gifi (accno,description) VALUES ('3980', 'Bestand Waren');
INSERT INTO gifi (accno,description) VALUES ('3990', 'Verrechnete Stoffkosten');
INSERT INTO gifi (accno,description) VALUES ('4000', 'Material-und Stoffverbrauch');
INSERT INTO gifi (accno,description) VALUES ('4100', 'Löhne und Gehälter');
INSERT INTO gifi (accno,description) VALUES ('4110', 'Löhne');
INSERT INTO gifi (accno,description) VALUES ('4120', 'Gehälter');
INSERT INTO gifi (accno,description) VALUES ('4124', 'Geschäftsführ.gehälter GmbH-Gesell.');
INSERT INTO gifi (accno,description) VALUES ('4125', 'Ehegattengehalt');
INSERT INTO gifi (accno,description) VALUES ('4126', 'Tantiemen');
INSERT INTO gifi (accno,description) VALUES ('4127', 'Geschäftsführergehälter');
INSERT INTO gifi (accno,description) VALUES ('4128', 'Vergütung a.angestellte Mitunterneh §15EStG.');
INSERT INTO gifi (accno,description) VALUES ('4130', 'Gesetzlich soziale Aufwendungen');
INSERT INTO gifi (accno,description) VALUES ('4137', 'Gesetz.sozi.Aufw.f.Mitunternehmen §15EStG');
INSERT INTO gifi (accno,description) VALUES ('4138', 'Beiträge zur Berufsgenossenschaftr');
INSERT INTO gifi (accno,description) VALUES ('4139', 'Ausgleichsabgabe i.S.d.Schwerbehinterdengesetzes');
INSERT INTO gifi (accno,description) VALUES ('4140', 'Freiwillig soziale Aufwendungen lohnsteuerfrei');
INSERT INTO gifi (accno,description) VALUES ('4145', 'Freiwillige sozi.Aufw.lohnsteuerpflichtig.');
INSERT INTO gifi (accno,description) VALUES ('4149', 'Pauschale Lohnsteuera.sons.Bezüge (z.B.Fahrtkostenzu)');
INSERT INTO gifi (accno,description) VALUES ('4150', 'Krankengeldzuschüsse');
INSERT INTO gifi (accno,description) VALUES ('4160', 'Versorgungskasse');
INSERT INTO gifi (accno,description) VALUES ('4165', 'Aufwendung f.Altersversorgung');
INSERT INTO gifi (accno,description) VALUES ('4167', 'Pauschale Lohnsteuer auf sonst.Bezüge(z.B.Direktversicherung');
INSERT INTO gifi (accno,description) VALUES ('4168', 'Aufwend.f.Altersversorgung f.Mitunternehmer §15EStG');
INSERT INTO gifi (accno,description) VALUES ('4169', 'Aufwendungen für Untersützung');
INSERT INTO gifi (accno,description) VALUES ('4170', 'Vermögenswirksame Leistungen');
INSERT INTO gifi (accno,description) VALUES ('4175', 'Fahrtkostenerst.Wohnung/Arbeitsstät');
INSERT INTO gifi (accno,description) VALUES ('4180', 'Bedienungsgelder');
INSERT INTO gifi (accno,description) VALUES ('4190', 'Aushilfslöhne');
INSERT INTO gifi (accno,description) VALUES ('4199', 'Lohnsteuer für Aushilfe');
INSERT INTO gifi (accno,description) VALUES ('4200', 'Raumkosten');
INSERT INTO gifi (accno,description) VALUES ('4210', 'Miete');
INSERT INTO gifi (accno,description) VALUES ('4218', 'Gewerbesteuerlich zu berücksichtigende Miete §8GewStG');
INSERT INTO gifi (accno,description) VALUES ('4219', 'Vergütungen an Mituntern. f.d.mietweise Überlassung ihrer WG §15EStG');
INSERT INTO gifi (accno,description) VALUES ('4220', 'Pacht');
INSERT INTO gifi (accno,description) VALUES ('4228', 'Gewerbesteuerlich zu berücks.Pacht §8GewStG');
INSERT INTO gifi (accno,description) VALUES ('4229', 'Vergütungen an Mituntern.f.d.pachtweise Überlassung ihrer WG§15EStG');
INSERT INTO gifi (accno,description) VALUES ('4230', 'Heizung');
INSERT INTO gifi (accno,description) VALUES ('4240', 'Gas,Strom, Wasser');
INSERT INTO gifi (accno,description) VALUES ('4250', 'Reinigung');
INSERT INTO gifi (accno,description) VALUES ('4260', 'Instandhaltung betrieb.Räume');
INSERT INTO gifi (accno,description) VALUES ('4270', 'Abgaben f.betrieb.genutz.Grundbesitz');
INSERT INTO gifi (accno,description) VALUES ('4280', 'Sonstige Raumkosten');
INSERT INTO gifi (accno,description) VALUES ('4300', 'Nicht abziehbare Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('4301', 'Nicht abziehbare Vorsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('4305', 'Nicht abziehbare Vorsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('4320', 'Gewerbesteuer');
INSERT INTO gifi (accno,description) VALUES ('4340', 'Sonstige Betriebssteuern');
INSERT INTO gifi (accno,description) VALUES ('4350', 'Verbrauchssteuer');
INSERT INTO gifi (accno,description) VALUES ('4355', 'Ökosteuer');
INSERT INTO gifi (accno,description) VALUES ('4360', 'Versicherungen');
INSERT INTO gifi (accno,description) VALUES ('4370', 'Nettoprä.f.Rückdeckung künf.Versorgungsleist.');
INSERT INTO gifi (accno,description) VALUES ('4380', 'Beiträge');
INSERT INTO gifi (accno,description) VALUES ('4390', 'Sonstige Abgaben');
INSERT INTO gifi (accno,description) VALUES ('4396', 'Steuerl.abzugs.Verspätungszuschl.u.Zwangsgelder');
INSERT INTO gifi (accno,description) VALUES ('4397', 'Steuerl.n.abzugsf.Verspätungszuschläge u.Zwangsgelder');
INSERT INTO gifi (accno,description) VALUES ('4500', 'Fahrzugkosten');
INSERT INTO gifi (accno,description) VALUES ('4510', 'Kfz-Steuer');
INSERT INTO gifi (accno,description) VALUES ('4520', 'Kfz-Versicherungen');
INSERT INTO gifi (accno,description) VALUES ('4530', 'Laufende Kfz-Betriebskosten');
INSERT INTO gifi (accno,description) VALUES ('4540', 'Kfz-Reparaturen');
INSERT INTO gifi (accno,description) VALUES ('4550', 'Garagenmiete');
INSERT INTO gifi (accno,description) VALUES ('4570', 'Fremdfahrzeuge');
INSERT INTO gifi (accno,description) VALUES ('4580', 'Sonstige Kfz-Kosten');
INSERT INTO gifi (accno,description) VALUES ('4600', 'Werbe-und Reisekosten');
INSERT INTO gifi (accno,description) VALUES ('4610', 'Werbekosten');
INSERT INTO gifi (accno,description) VALUES ('4630', 'Geschenke bis 40 EUR');
INSERT INTO gifi (accno,description) VALUES ('4635', 'Geschenke über 40 EUR');
INSERT INTO gifi (accno,description) VALUES ('4638', 'Geschenke ausschließl.betrieb.genut');
INSERT INTO gifi (accno,description) VALUES ('4640', 'Repräsentationskosten');
INSERT INTO gifi (accno,description) VALUES ('4650', 'Bewirtungskosten');
INSERT INTO gifi (accno,description) VALUES ('4653', 'Aufmerksamkeiten');
INSERT INTO gifi (accno,description) VALUES ('4654', 'Nicht abzugsfähige Bewirtungskosten');
INSERT INTO gifi (accno,description) VALUES ('4655', 'Nicht abzugsfähige Betriebsausgaben');
INSERT INTO gifi (accno,description) VALUES ('4660', 'Reisekosten Arbeitnehmer');
INSERT INTO gifi (accno,description) VALUES ('4663', 'Reisekosten Arbeitn.m.Vorsteuerabzu f.öffentl.Verkehrsm.');
INSERT INTO gifi (accno,description) VALUES ('4664', 'Reisekosten Arbeitn.Verpflegungmehr');
INSERT INTO gifi (accno,description) VALUES ('4666', 'Reisekosten Arbeitn.Übernachtungsaufwand');
INSERT INTO gifi (accno,description) VALUES ('4668', 'Kilometerentgelderstattung Arbeitnehmer');
INSERT INTO gifi (accno,description) VALUES ('4670', 'Reisekosten Unternehmer');
INSERT INTO gifi (accno,description) VALUES ('4673', 'Reisek.Untern.m.Vorsteuerabzug (f.öffentl.Verkehrsm.');
INSERT INTO gifi (accno,description) VALUES ('4674', 'Reisekosten Untern.Verpflegungsmehr');
INSERT INTO gifi (accno,description) VALUES ('4676', 'Reisekosten Untern.Übernachtungsauf');
INSERT INTO gifi (accno,description) VALUES ('4678', 'Kilometererstattungsgeld Unternehme');
INSERT INTO gifi (accno,description) VALUES ('4700', 'Kosten der Warenabgabe');
INSERT INTO gifi (accno,description) VALUES ('4710', 'Verpackungsmaterial');
INSERT INTO gifi (accno,description) VALUES ('4730', 'Ausgangsfracht');
INSERT INTO gifi (accno,description) VALUES ('4750', 'Transportversicherung');
INSERT INTO gifi (accno,description) VALUES ('4760', 'Verkaufsprovision');
INSERT INTO gifi (accno,description) VALUES ('4780', 'Fremdarbeiten');
INSERT INTO gifi (accno,description) VALUES ('4790', 'Aufwand für Gewährleistungen');
INSERT INTO gifi (accno,description) VALUES ('4800', 'Rep.u.Instandhaltungen v.techn.Anlagen u.Maschinen');
INSERT INTO gifi (accno,description) VALUES ('4805', 'Rep.u.Instandhaltungen v.and.Anlagen u.Betriebs-u.Geschäftsausst.');
INSERT INTO gifi (accno,description) VALUES ('4806', 'Wartungskosten für Hard-u.Software');
INSERT INTO gifi (accno,description) VALUES ('4809', 'Sonstige Reparaturen u.Instandhalt.');
INSERT INTO gifi (accno,description) VALUES ('4810', 'Mietleasing');
INSERT INTO gifi (accno,description) VALUES ('4814', 'Gewerbesteuerlich zu berücks.Mietleasing §8GewStG');
INSERT INTO gifi (accno,description) VALUES ('4815', 'Kaufleasing');
INSERT INTO gifi (accno,description) VALUES ('4820', 'AfA a.Aufw.f.d.Inga.u.Erw.Geschäfts');
INSERT INTO gifi (accno,description) VALUES ('4821', 'AfA a.Aufw.f.d.Währungsumst.a.Euro');
INSERT INTO gifi (accno,description) VALUES ('4822', 'Abschreibungen a.immat.Vermögensgeg');
INSERT INTO gifi (accno,description) VALUES ('4824', 'Abschreibung a.d.Geschäft-o.Firmenw');
INSERT INTO gifi (accno,description) VALUES ('4826', 'Außerplan.AfA a.immat.Vermögensgeg.');
INSERT INTO gifi (accno,description) VALUES ('4830', 'Abschreibungen auf Sachanlagen');
INSERT INTO gifi (accno,description) VALUES ('4840', 'Außerplanmäßig Abschr.a.Sachanlagen');
INSERT INTO gifi (accno,description) VALUES ('4850', 'Abschr.a.Sachanl.aufgr.steuerl.Sondervorschriften');
INSERT INTO gifi (accno,description) VALUES ('4855', 'Sofortabschreibung GWG');
INSERT INTO gifi (accno,description) VALUES ('4860', 'Abschreibungen auf aktivierte GWG');
INSERT INTO gifi (accno,description) VALUES ('4865', 'Außerplanmäßige AFA auf aktivierte geringwertige WG');
INSERT INTO gifi (accno,description) VALUES ('4870', 'Abschreibungen auf Finanzanlagen');
INSERT INTO gifi (accno,description) VALUES ('4871', 'Abschreibungen a.Finanzanlagen 100%/50% n.abzugsfähig');
INSERT INTO gifi (accno,description) VALUES ('4872', 'Abschreibungen an Mitunternehmerschaften §8 GewStG');
INSERT INTO gifi (accno,description) VALUES ('4873', 'Abschreibungen a.Finanzanlagen a.Grund steuerl.Sondervorschr.100%/50%n.abzf.');
INSERT INTO gifi (accno,description) VALUES ('4874', 'Abschreibungen a.Finanzanlagen auf Grund steuerl.Sondervorschriften');
INSERT INTO gifi (accno,description) VALUES ('4875', 'Abschr.a.Wertp.d.Umlaufvermögens');
INSERT INTO gifi (accno,description) VALUES ('4876', 'Abschr.a.Wertpapiere d.Umlaufverm. 100%/50% n.abzugsf.');
INSERT INTO gifi (accno,description) VALUES ('4879', 'Vorwegnahme künftiger Wertschwank.b.Wertpap.d.Umlaufvermögens');
INSERT INTO gifi (accno,description) VALUES ('4880', 'Abschreibungen auf Umlaufverm. o.Wertpapiere (soweit unübl.Höhe');
INSERT INTO gifi (accno,description) VALUES ('4882', 'Abschreibungen a.Umlaufverm.,steuerrechtl. bedingt (soweit unübl.Höhe');
INSERT INTO gifi (accno,description) VALUES ('4885', 'Vorwegnahme künft.Wertschwank.i.Umlaufverm.außer  Vorräte u.Wertpap.d.UV');
INSERT INTO gifi (accno,description) VALUES ('4886', 'Abschr.a.UV außer Vorräte u.Wertpap.d.UV (soweit übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('4887', 'Abschr.a.UV steuerrechtl.bedingt(soweit übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('4890', 'Vorwegnahme künft.Wertschwank. i.UV (soweit übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('4900', 'Sonstige betriebliche Aufwendungen');
INSERT INTO gifi (accno,description) VALUES ('4905', 'Sons.Aufw.betriebl. und regelmäßig');
INSERT INTO gifi (accno,description) VALUES ('4909', 'Fremdleistungen');
INSERT INTO gifi (accno,description) VALUES ('4910', 'Porto');
INSERT INTO gifi (accno,description) VALUES ('4920', 'Telefon');
INSERT INTO gifi (accno,description) VALUES ('4925', 'Telefax');
INSERT INTO gifi (accno,description) VALUES ('4930', 'Bürobedarf');
INSERT INTO gifi (accno,description) VALUES ('4940', 'Zeitschriften, Bücher');
INSERT INTO gifi (accno,description) VALUES ('4945', 'Fortbildungskosten');
INSERT INTO gifi (accno,description) VALUES ('4946', 'Freiwillige Sozialleistungen');
INSERT INTO gifi (accno,description) VALUES ('4948', 'Vergütungen an freiberufl.Mitunternehmer §15EStG');
INSERT INTO gifi (accno,description) VALUES ('4949', 'Haftungsvergütung an Mitunternehmer §15EStG');
INSERT INTO gifi (accno,description) VALUES ('4950', 'Rechts- und Beratungskosten');
INSERT INTO gifi (accno,description) VALUES ('4955', 'Buchführungskosten');
INSERT INTO gifi (accno,description) VALUES ('4957', 'Abschluß- und Prüfungskosten');
INSERT INTO gifi (accno,description) VALUES ('4960', 'Mieten für Einrichtungen');
INSERT INTO gifi (accno,description) VALUES ('4968', 'Gewerbesteuerl.zu berückst.Miete f.Einricht.§8GewStG');
INSERT INTO gifi (accno,description) VALUES ('4969', 'Aufwend.f.Abraum-u.Abfallbeseitigung');
INSERT INTO gifi (accno,description) VALUES ('4970', 'Nebenkosten des Geldverkehrs');
INSERT INTO gifi (accno,description) VALUES ('4975', 'Aufwend.a.Anteilen an Kap.Ges.100%/50% n.abzugsf.(inländ.Kap.Ges.');
INSERT INTO gifi (accno,description) VALUES ('4976', 'Aufwend.a.d.Veräußerung v.Anteilen an Kap.Ges.100%/50% n.abzugsf.');
INSERT INTO gifi (accno,description) VALUES ('4980', 'Betriebsbedarf');
INSERT INTO gifi (accno,description) VALUES ('4985', 'Werkzeuge und Kleingeräte');
INSERT INTO gifi (accno,description) VALUES ('4990', 'Kalkulatorischer Unternehmerlohn');
INSERT INTO gifi (accno,description) VALUES ('4992', 'Kalkulatorische Zinsen');
INSERT INTO gifi (accno,description) VALUES ('4993', 'Kalkulatorische Aschreibungen');
INSERT INTO gifi (accno,description) VALUES ('4994', 'Kalkulatorische Wagnisse');
INSERT INTO gifi (accno,description) VALUES ('4995', 'Kalkulatorischer Lohn f.unentgeltl.Mitarbeiter');
INSERT INTO gifi (accno,description) VALUES ('4996', 'Herstellungskosten');
INSERT INTO gifi (accno,description) VALUES ('4997', 'Verwaltungskosten');
INSERT INTO gifi (accno,description) VALUES ('4998', 'Vertriebskosten');
INSERT INTO gifi (accno,description) VALUES ('7000', 'Unfertige Erzeu.unfert.Leistungen (Bestand)');
INSERT INTO gifi (accno,description) VALUES ('7050', 'Unfertige Erzeugnisse (Bestand)');
INSERT INTO gifi (accno,description) VALUES ('7080', 'Unfertige Leistungen (Bestand)');
INSERT INTO gifi (accno,description) VALUES ('7090', 'In Ausführung befindl. Bauaufträge');
INSERT INTO gifi (accno,description) VALUES ('7095', 'In Arbeit befindliche Aufträge');
INSERT INTO gifi (accno,description) VALUES ('7100', 'Fertige Erzeugnisse und Waren(Bestand)');
INSERT INTO gifi (accno,description) VALUES ('7110', 'Fertige Erzeugnisse (Bestand)');
INSERT INTO gifi (accno,description) VALUES ('7140', 'Waren (Bestand)');
INSERT INTO gifi (accno,description) VALUES ('8100', 'Steuerfreie Umsätze §4Nr.8ff UstG');
INSERT INTO gifi (accno,description) VALUES ('8110', 'Sonstige steuerfreie Umsätze Inland');
INSERT INTO gifi (accno,description) VALUES ('8120', 'Steuerfreie Umsätze §4Nr.1a UstG');
INSERT INTO gifi (accno,description) VALUES ('8125', 'Steuerfrei innergem. Lieferungen §41bUStG');
INSERT INTO gifi (accno,description) VALUES ('8130', 'Liefe.d.1.Abnehm.bei innergem.Dreiecksg §25b2UStG');
INSERT INTO gifi (accno,description) VALUES ('8135', 'Steuerfr.innergem.Lief.v.Neufahrz.an Abn.o.USt-Ident-Nr.');
INSERT INTO gifi (accno,description) VALUES ('8140', 'Steuerfreie Umsätze Offshore usw.');
INSERT INTO gifi (accno,description) VALUES ('8150', 'Sonstige steuerfreie Umsätze §42-7UStG');
INSERT INTO gifi (accno,description) VALUES ('8196', 'Erlöse aus Geldspielautomaten 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('8200', 'Erlöse');
INSERT INTO gifi (accno,description) VALUES ('8300', 'Erlöse 7%USt');
INSERT INTO gifi (accno,description) VALUES ('8310', 'Erlöse Inland stpfl. EG-Lieferung7%');
INSERT INTO gifi (accno,description) VALUES ('8315', 'Erlös Inland stpfl.EG-Lieferung 16%');
INSERT INTO gifi (accno,description) VALUES ('8320', 'Erlöse aus im and.EG-Land steuerpfl.Lieferungen');
INSERT INTO gifi (accno,description) VALUES ('8339', 'Erl.EG-Land stpfl.so.Leist.(0-Regl)');
INSERT INTO gifi (accno,description) VALUES ('8400', 'Erlöse 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('8500', 'Provisionserlöse');
INSERT INTO gifi (accno,description) VALUES ('8504', 'Provisionserlöse,steuerfrei (§4Nr.8ff.UStG)');
INSERT INTO gifi (accno,description) VALUES ('8505', 'Provisionserlöse,steuerfrei (§4Nr.5UStG)');
INSERT INTO gifi (accno,description) VALUES ('8506', 'Provisionserlöse 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('8508', 'Provisionserlöse 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('8520', 'Erlöse Abfallverwertung');
INSERT INTO gifi (accno,description) VALUES ('8540', 'Erlös Leergut');
INSERT INTO gifi (accno,description) VALUES ('8590', 'Verrechnete sons. Sachbezüge keine Waren');
INSERT INTO gifi (accno,description) VALUES ('8591', 'Sachbezüge 7% Ust (Waren)');
INSERT INTO gifi (accno,description) VALUES ('8595', 'Sachbezüge 16% Ust (Waren)');
INSERT INTO gifi (accno,description) VALUES ('8600', 'Sonstige Erlöse betriebl.u.regelmäß');
INSERT INTO gifi (accno,description) VALUES ('8610', 'Verrechnete sonstige Sachbezüge');
INSERT INTO gifi (accno,description) VALUES ('8611', 'Verr.sons.Sachbezüge 16%USt(Kfz-Gestellung)');
INSERT INTO gifi (accno,description) VALUES ('8614', 'Verrechnete sons.Sachbezüge o. USt');
INSERT INTO gifi (accno,description) VALUES ('8625', 'Sons. Erlöse betriebl.u.reg.steuerf');
INSERT INTO gifi (accno,description) VALUES ('8650', 'Erlöse Zinsen und Diskotspesen');
INSERT INTO gifi (accno,description) VALUES ('8630', 'Sonst.Erlöse betriebl.u.regelmäßig 7% USt');
INSERT INTO gifi (accno,description) VALUES ('8640', 'Sonst.Erlöse betriebl.u.regelmäßig 16% USt');
INSERT INTO gifi (accno,description) VALUES ('8660', 'Erlöse Zinsen u.Diskontspesen aus verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('8700', 'Erlösschmälerungen');
INSERT INTO gifi (accno,description) VALUES ('8705', 'Erlösschmälerungen aus steuerfr.Umsätzen §4 Nr.1a UStG');
INSERT INTO gifi (accno,description) VALUES ('8710', 'Erlösschmälerung 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('8720', 'Erlösschmälerung 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('8724', 'Erlösschmäler.a.stfrei.IG Lieferung');
INSERT INTO gifi (accno,description) VALUES ('8725', 'Erlösschmä.Inl.stpfl.EG-Lief. 7%USt');
INSERT INTO gifi (accno,description) VALUES ('8726', 'Erlösschmä.Inl.stpfl.EG-Lief.16%USt');
INSERT INTO gifi (accno,description) VALUES ('8727', 'Erlösschmä.and.EG Land stpfl.Liefer');
INSERT INTO gifi (accno,description) VALUES ('8729', 'Erlösschmälerungen aus im Inland steuerpfl.EG-Lief.15% USt');
INSERT INTO gifi (accno,description) VALUES ('8730', 'Gewährte Skonti');
INSERT INTO gifi (accno,description) VALUES ('8731', 'Gewährte Skonti 7% USt');
INSERT INTO gifi (accno,description) VALUES ('8735', 'Gewährte Skonti 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('8740', 'Gewährte Boni');
INSERT INTO gifi (accno,description) VALUES ('8750', 'Gewährte Boni 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('8760', 'Gewährte Boni 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('8770', 'Gewährte Rabatte');
INSERT INTO gifi (accno,description) VALUES ('8780', 'Gewährte Rabatte 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('8790', 'Gewährte Rabatte 16% Ust.');
INSERT INTO gifi (accno,description) VALUES ('8800', 'Erlöse aus Anlagenverkäufen');
INSERT INTO gifi (accno,description) VALUES ('8801', 'Erlöse aus Anlagenverkäufen Sachanl.verm.b.Buchverl.16%USt.');
INSERT INTO gifi (accno,description) VALUES ('8817', 'Erlöse aus Verkäufen immat.VG (bei Buchverlust)');
INSERT INTO gifi (accno,description) VALUES ('8818', 'Erlöse aus Verkäufen Finanzanlagen (bei Buchverlust)');
INSERT INTO gifi (accno,description) VALUES ('8819', 'Erlöse aus Verkäufen Finanzanl.100%/50% nicht abzugsf.(b.Buchverlust)');
INSERT INTO gifi (accno,description) VALUES ('8820', 'Erlöse aus Anlageverkäufen Sachanl.verm.b.Buchgewinn16%Ust');
INSERT INTO gifi (accno,description) VALUES ('8829', 'Erl.a.Anlagenverk.bei Buchgewinn');
INSERT INTO gifi (accno,description) VALUES ('8837', 'Erlöse aus Verk.immat.VG (bei Buchgewinn)');
INSERT INTO gifi (accno,description) VALUES ('8838', 'Erlöse aus Verkäufen Finanzanlagen (bei Buchgewinn)');
INSERT INTO gifi (accno,description) VALUES ('8839', 'Erlöse aus Verkäufen Finanzanlagen 100%/50% steuerfrei (bei Buchgewinn)');
INSERT INTO gifi (accno,description) VALUES ('8900', 'Unentgeldliche Wertabgaben');
INSERT INTO gifi (accno,description) VALUES ('8905', 'Entnahme v. Gegenst.o.USt.');
INSERT INTO gifi (accno,description) VALUES ('8910', 'Entnahme des Untern.f.Zwecke ausserh.d.Untern 16%(Waren)');
INSERT INTO gifi (accno,description) VALUES ('8915', 'Entnah.d.Untern.f.Zwecke ausserh.d.Untern.7%USt');
INSERT INTO gifi (accno,description) VALUES ('8919', 'Entnahme durch den Untern.f.Zwecke außerhalb d.Untern.(Waren)o.USt');
INSERT INTO gifi (accno,description) VALUES ('8920', 'Verw.v.Gegens.f.Zwecke ausserh.d.Untern.16%USt.');
INSERT INTO gifi (accno,description) VALUES ('8924', 'Verwendung v.Gegenständen f.Zwecke außerhalb d.Untern.o.USt.');
INSERT INTO gifi (accno,description) VALUES ('8925', 'Unentgeldl.Erbring.sons.Leis.16%USt');
INSERT INTO gifi (accno,description) VALUES ('8929', 'Unentgeltliche Erbringung einer sonst.Leistung o.USt.');
INSERT INTO gifi (accno,description) VALUES ('8930', 'Verwendung v.Gegenst.f.Zwecke außerhalb d.Unternehmens 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('8932', 'Unentgelt.Erbring.sons.Leist. 7%Ust');
INSERT INTO gifi (accno,description) VALUES ('8935', 'Unentgeltl.Zuwend.v.Gegens. 16% Ust');
INSERT INTO gifi (accno,description) VALUES ('8939', 'Unentgeldl.Zuw.v.Gegens.ohne Ust');
INSERT INTO gifi (accno,description) VALUES ('8940', 'Unentgeltl.Zuw.v Waren 16% Ust');
INSERT INTO gifi (accno,description) VALUES ('8945', 'Unentgeltl.Zuw.von Waren 7% Ust');
INSERT INTO gifi (accno,description) VALUES ('8949', 'Unentgeltl.Zuwendung v.Waren o.USt.');
INSERT INTO gifi (accno,description) VALUES ('8950', 'Nicht steuerbare Umsätze');
INSERT INTO gifi (accno,description) VALUES ('8955', 'Umsatzsteuervergütungen');
INSERT INTO gifi (accno,description) VALUES ('8960', 'Bestandsveränderung-unfertige Erzeu');
INSERT INTO gifi (accno,description) VALUES ('8970', 'Bestandsveränderung-unfertige Leist');
INSERT INTO gifi (accno,description) VALUES ('8975', 'Bestandsverä.i.Ausfü.befi.Bauaufträ');
INSERT INTO gifi (accno,description) VALUES ('8977', 'Bestandsverä.i.Arbeit befindl.Auftr');
INSERT INTO gifi (accno,description) VALUES ('8980', 'Bestandsverä.fertige Erzeugnisse');
INSERT INTO gifi (accno,description) VALUES ('8990', 'Andere aktivierte Eigenleistungen');
INSERT INTO gifi (accno,description) VALUES ('9000', 'Saldenverträge,Sachkonten');
INSERT INTO gifi (accno,description) VALUES ('9008', 'Saldenverträge,Debitoren');
INSERT INTO gifi (accno,description) VALUES ('9009', 'Saldenverträge,Kreditoren');
INSERT INTO gifi (accno,description) VALUES ('9060', 'Offene Posten aus 1990');
INSERT INTO gifi (accno,description) VALUES ('9069', 'Offene Posten aus 1999');
INSERT INTO gifi (accno,description) VALUES ('9070', 'Offene Posten aus 2000');
INSERT INTO gifi (accno,description) VALUES ('9071', 'Offene Posten aus 2001');
INSERT INTO gifi (accno,description) VALUES ('9072', 'Offene Posten aus 2002');
INSERT INTO gifi (accno,description) VALUES ('9090', 'Summenvortragskonto');
INSERT INTO gifi (accno,description) VALUES ('9220', 'Gezeichnetes kapital in DM');
INSERT INTO gifi (accno,description) VALUES ('9221', 'Gezeichnetes Kapital in Euro');
INSERT INTO gifi (accno,description) VALUES ('9229', 'Gegenkonto zu 9220-9221');
INSERT INTO gifi (accno,description) VALUES ('9230', 'Baukostenzuschüsse');
INSERT INTO gifi (accno,description) VALUES ('9232', 'Investitionszulagen');
INSERT INTO gifi (accno,description) VALUES ('9234', 'Investitionszuschüsse');
INSERT INTO gifi (accno,description) VALUES ('9240', 'Investitionsverbindlichkeiten bei den Leistungsvblk.');
INSERT INTO gifi (accno,description) VALUES ('9241', 'Investitionsvblk.aus Sachanlagenkäufen b.Leistungsvblk.');
INSERT INTO gifi (accno,description) VALUES ('9242', 'Investitionsvblk.aus Käufen v.immat.VG bei Leistungsvblk.');
INSERT INTO gifi (accno,description) VALUES ('9243', 'Investitionsvblk.aus Käufen v.Finanzanlagen bei Leistungsvblk.');
INSERT INTO gifi (accno,description) VALUES ('9244', 'Gegenkonto zu Konten 9240-43');
INSERT INTO gifi (accno,description) VALUES ('9245', 'Forde.a.Sachanlageverk.b.Sonst.VG');
INSERT INTO gifi (accno,description) VALUES ('9246', 'Ford.a.Verk.immat.VG b.sonst.VG');
INSERT INTO gifi (accno,description) VALUES ('9247', 'Ford.a.Verk.v.Finanzanlagen b.sonst.VG');
INSERT INTO gifi (accno,description) VALUES ('9249', 'Gegenkonto zu Konten 9245-47');
INSERT INTO gifi (accno,description) VALUES ('9250', 'Eigenkapitalersetzende Gesellschafterdarlehen');
INSERT INTO gifi (accno,description) VALUES ('9255', 'Ungesicherte Gesellschafterdarl.m.Restlaufz. größer als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('9259', 'Gegenkonto zu 9250 und 9255');
INSERT INTO gifi (accno,description) VALUES ('9260', 'Kurzfristige Rückstellung');
INSERT INTO gifi (accno,description) VALUES ('9262', 'Mittelfristige Rückstellung');
INSERT INTO gifi (accno,description) VALUES ('9264', 'Langfristige Rückstellungen');
INSERT INTO gifi (accno,description) VALUES ('9269', 'Gegenkonto zu Konten 9260-9268');
INSERT INTO gifi (accno,description) VALUES ('9270', 'Gegenkonto zu 9271-9278 (Soll-Buchung)');
INSERT INTO gifi (accno,description) VALUES ('9271', 'Vblk.aus der Begebung u.Übertragung v.Wechseln');
INSERT INTO gifi (accno,description) VALUES ('9272', 'Vblk.a.d.Begebung u.Übertragung v.Wechseln gegenüb.verb.Untern.');
INSERT INTO gifi (accno,description) VALUES ('9273', 'Vblk.a.Bürgschaften,Wechseln-u.Scheckbürgschaften');
INSERT INTO gifi (accno,description) VALUES ('9274', 'Vblk.a.Bürgschaften,Wechseln-u.Scheckbürgschaften geg.verb.Untern.');
INSERT INTO gifi (accno,description) VALUES ('9275', 'Vblk.aus Gewährleistungsverträgen');
INSERT INTO gifi (accno,description) VALUES ('9276', 'Vblk.a.Gewährleistungsverträgen geg.verb.Untern.');
INSERT INTO gifi (accno,description) VALUES ('9277', 'Haftung aus der Bestellung v.Sicherheiten f.fremde Vblk.');
INSERT INTO gifi (accno,description) VALUES ('9278', 'Haftung a.d.Bestellung v.Sicherh.f.fremde Vblk.geg.verb.Untern.');
INSERT INTO gifi (accno,description) VALUES ('9280', 'Gegenkonto zu 9281-9284');
INSERT INTO gifi (accno,description) VALUES ('9281', 'Verpfl.a.Miet-und Leasinggesch.');
INSERT INTO gifi (accno,description) VALUES ('9282', 'Verpfl.geg.verb.Unternehmen');
INSERT INTO gifi (accno,description) VALUES ('9283', 'Andere Verpflichtungen gem. §285 Nr.3HGB');
INSERT INTO gifi (accno,description) VALUES ('9284', 'And.Verpfl.gem.§285 3 HGB verb.Untern.');
INSERT INTO gifi (accno,description) VALUES ('9290', 'Statistisches Konto steuerfreie Auslagen');
INSERT INTO gifi (accno,description) VALUES ('9291', 'Gegenkonto zu 9290');
INSERT INTO gifi (accno,description) VALUES ('9292', 'Statistisches Konto Fremdgeld');
INSERT INTO gifi (accno,description) VALUES ('9293', 'Gegenkonto zu 9292');
INSERT INTO gifi (accno,description) VALUES ('9880', 'Ausgleichsposten f.aktivierte eigene Anteile');
INSERT INTO gifi (accno,description) VALUES ('9882', 'Ausgleichsposten f.aktivierte Bilanzierungshilfen');
