-- DATEV SKR04
-- IT Systems Service http://www.itsystemsservice.de
--
INSERT INTO gifi (accno,description) VALUES ('0135', 'EDV-Software');
INSERT INTO gifi (accno,description) VALUES ('0150', 'Geschäfts- oder Firmenwert');
INSERT INTO gifi (accno,description) VALUES ('0240', 'Geschäftsbauten');
INSERT INTO gifi (accno,description) VALUES ('0400', 'Techn.Anlagen und Maschinen');
INSERT INTO gifi (accno,description) VALUES ('0440', 'Maschinen');
INSERT INTO gifi (accno,description) VALUES ('0500', 'Betriebs- und Geschäftsausstattung');
INSERT INTO gifi (accno,description) VALUES ('0510', 'Andere Anlagen');
INSERT INTO gifi (accno,description) VALUES ('0520', 'PKW');
INSERT INTO gifi (accno,description) VALUES ('0560', 'Sonst.Transportmittel');
INSERT INTO gifi (accno,description) VALUES ('0620', 'Werkzeuge');
INSERT INTO gifi (accno,description) VALUES ('0640', 'Ladeneinrichtung');
INSERT INTO gifi (accno,description) VALUES ('0650', 'Büroeinrichtung');
INSERT INTO gifi (accno,description) VALUES ('0670', 'Geringwertige Wirtschaftsg. b. 410 Euro');
INSERT INTO gifi (accno,description) VALUES ('1000', 'Roh,-Hilfs,-und Betriebsstoffe');
INSERT INTO gifi (accno,description) VALUES ('1140', 'Waren');
INSERT INTO gifi (accno,description) VALUES ('1200', 'Ford. aus Lieferungen und Leistungen');
INSERT INTO gifi (accno,description) VALUES ('1215', 'Ford.a.LuL z.allg.USt-Satz');
INSERT INTO gifi (accno,description) VALUES ('1216', 'Ford.a.LuL z.erm.USt.-Satz (EÜR)');
INSERT INTO gifi (accno,description) VALUES ('1217', 'Ford.a.steuerfr.od.nicht steuerb.LuL (EÜR)');
INSERT INTO gifi (accno,description) VALUES ('1218', 'Ford.a.LuL gem.§24UStG(EÜR)');
INSERT INTO gifi (accno,description) VALUES ('1219', 'Gegenkto. bei Aufteil.d.Ford.n.Steuers.(EÜR)');
INSERT INTO gifi (accno,description) VALUES ('1220', 'Ford.n.§11(1)2EStG f.§4/3 EStG');
INSERT INTO gifi (accno,description) VALUES ('1248', 'Pauschalwertbe.z.Ford.bis1J.');
INSERT INTO gifi (accno,description) VALUES ('1249', 'Pauschalwertbe.z.Ford.ueb1J.');
INSERT INTO gifi (accno,description) VALUES ('1370', 'Durchlaufende Posten');
INSERT INTO gifi (accno,description) VALUES ('1374', 'Fremdgeld');
INSERT INTO gifi (accno,description) VALUES ('1400', 'Abziehbare Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('1401', 'Abziebare Vorsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('1402', 'Abziehbare Vorsteuer aus EG-Erwerb');
INSERT INTO gifi (accno,description) VALUES ('1403', 'Abziehbare Vorsteuer aus EG-Erwerb 16%');
INSERT INTO gifi (accno,description) VALUES ('1405', 'Abziehbare Vorsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('1407', 'Abziehb.Vorst.n.allgem.Durchschnittssätzen UStVA Kz.63');
INSERT INTO gifi (accno,description) VALUES ('1408', 'Abziehbare Vorsteuer n.§13b UStG');
INSERT INTO gifi (accno,description) VALUES ('1409', 'Abziehbare Vorsteuer n.§13b UStG 16%');
INSERT INTO gifi (accno,description) VALUES ('1433', 'Bezahlte Einfuhrumsatzsteuer');
INSERT INTO gifi (accno,description) VALUES ('1460', 'Geldtransit');
INSERT INTO gifi (accno,description) VALUES ('1480', 'Gegenkonto Vorsteuer §4/3 EStG');
INSERT INTO gifi (accno,description) VALUES ('1481', 'Auflösung Vorst.a.Vorjahr §4/3 EStG');
INSERT INTO gifi (accno,description) VALUES ('1482', 'Vorst.aus Investitionen §4/3 EStG');
INSERT INTO gifi (accno,description) VALUES ('1484', 'abziehb.VorSt EU-Erwerb Neufzg.b.Lief. o. USt.Ident.Nr');
INSERT INTO gifi (accno,description) VALUES ('1600', 'Kasse');
INSERT INTO gifi (accno,description) VALUES ('1800', 'Bank');
INSERT INTO gifi (accno,description) VALUES ('2100', 'Privatentnahmen allgemein');
INSERT INTO gifi (accno,description) VALUES ('2150', 'Privatsteuern');
INSERT INTO gifi (accno,description) VALUES ('2180', 'Privateinlagen');
INSERT INTO gifi (accno,description) VALUES ('2200', 'Sonderausgaben beschränkt abzugsfähig');
INSERT INTO gifi (accno,description) VALUES ('2230', 'Sonderausgaben unbeschr. abzugsfähig');
INSERT INTO gifi (accno,description) VALUES ('2250', 'Zuwendungen, Spenden');
INSERT INTO gifi (accno,description) VALUES ('2953', 'Satzungsm.Rücklagen 0% Vorbelast.EK02');
INSERT INTO gifi (accno,description) VALUES ('3150', 'Verbindl.gegenüber Kreditinstituten');
INSERT INTO gifi (accno,description) VALUES ('3151', '- Restlaufzeit b.1 Jahr');
INSERT INTO gifi (accno,description) VALUES ('3160', '- Restlaufzeit 1 bis 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('3170', '- Restlaufzeit grösser als 5 Jahre');
INSERT INTO gifi (accno,description) VALUES ('3300', 'Verbindlichkeiten aus Lief.u.Leist.');
INSERT INTO gifi (accno,description) VALUES ('3305', 'Vblk.a.LuL z.allg.Umsatzsteuersatz (EÜR)');
INSERT INTO gifi (accno,description) VALUES ('3306', 'Vblk.a.LuL zum erm.Umsatzsteuersatz (EÜR)');
INSERT INTO gifi (accno,description) VALUES ('3307', 'Vblk.a.LuL ohne Vorsteuer (EÜR)');
INSERT INTO gifi (accno,description) VALUES ('3309', 'Gegenkonto 1605-1607 b.Aufteilung d.Vblk.n.Steuers.(EÜR)');
INSERT INTO gifi (accno,description) VALUES ('3800', 'Umsatzsteuer');
INSERT INTO gifi (accno,description) VALUES ('3801', 'Umsatzsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('3802', 'Umsatzsteuer aus EG-Erwerb');
INSERT INTO gifi (accno,description) VALUES ('3803', 'Umsatzsteuer aus EG-Erwerb 16%');
INSERT INTO gifi (accno,description) VALUES ('3805', 'Umsatzsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('3817', 'Umsatzsteuer a.i.anderen EG-Land stpfl.Lieferungen');
INSERT INTO gifi (accno,description) VALUES ('3820', 'Umsatzsteuer-Vorauszahlungen');
INSERT INTO gifi (accno,description) VALUES ('3830', 'Umsatzsteuer-Vorauszahlungen 1/11');
INSERT INTO gifi (accno,description) VALUES ('3833', 'Umsatzsteuer n.§13b UStG');
INSERT INTO gifi (accno,description) VALUES ('3841', 'Umsatzsteuer Vorjahr');
INSERT INTO gifi (accno,description) VALUES ('3845', 'Umsatzsteuer frühere Jahre');
INSERT INTO gifi (accno,description) VALUES ('4110', 'Sonstige steuerfreie Umsätze Inland');
INSERT INTO gifi (accno,description) VALUES ('4120', 'Steuerfreie Umsätze §4Nr.1a UstG');
INSERT INTO gifi (accno,description) VALUES ('4125', 'Steuerfrei innergem. Lieferungen §41bUStG');
INSERT INTO gifi (accno,description) VALUES ('4130', 'Liefe.d.1.Abnehm.bei innergem.Dreiecksg §25b2UStG');
INSERT INTO gifi (accno,description) VALUES ('4135', 'Steuerfr.innergem.Lief.v.Neufahrz.an Abn.o.USt-Ident-Nr.');
INSERT INTO gifi (accno,description) VALUES ('4140', 'Steuerfreie Umsätze Offshore usw.');
INSERT INTO gifi (accno,description) VALUES ('4150', 'Sonstige steuerfreie Umsätze §42-7UStG');
INSERT INTO gifi (accno,description) VALUES ('4180', 'Erlöse,die mit den Durchschnittssätzen d.§24UStG vers.werd.');
INSERT INTO gifi (accno,description) VALUES ('4185', 'Erlöse als Kleinunternehmer i.S.d.§19(1)UStG');
INSERT INTO gifi (accno,description) VALUES ('4200', 'Erlöse');
INSERT INTO gifi (accno,description) VALUES ('4300', 'Erlöse 7%USt');
INSERT INTO gifi (accno,description) VALUES ('4310', 'Erlöse Inland stpfl. EG-Lieferung7%');
INSERT INTO gifi (accno,description) VALUES ('4315', 'Erlös Inland stpfl.EG-Lieferung 16%');
INSERT INTO gifi (accno,description) VALUES ('4320', 'Erlöse aus im and.EG-Land steuerpfl.Lieferungen');
INSERT INTO gifi (accno,description) VALUES ('4400', 'Erlöse 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('4500', 'Provisionserlöse');
INSERT INTO gifi (accno,description) VALUES ('4504', 'Provisionserlöse,steuerfrei (§4Nr.8ff.UStG)');
INSERT INTO gifi (accno,description) VALUES ('4505', 'Provisionserlöse,steuerfrei (§4Nr.5UStG)');
INSERT INTO gifi (accno,description) VALUES ('4506', 'Provisionserlöse 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('4508', 'Provisionserlöse 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('4510', 'Erlöse Abfallverwertung');
INSERT INTO gifi (accno,description) VALUES ('4520', 'Erlös Leergut');
INSERT INTO gifi (accno,description) VALUES ('4580', 'Erlöse zum allg.Umsatzsteuersatz (EÜR)');
INSERT INTO gifi (accno,description) VALUES ('4581', 'Erlöse zum ermä.Umsatzsteuersatz (EÜR)');
INSERT INTO gifi (accno,description) VALUES ('4582', 'Erlöse steuerfrei u.nicht steuerbar (EÜR)');
INSERT INTO gifi (accno,description) VALUES ('4589', 'Gegenkonto 8580-8582 b.Aufteilung d.Erlöse n.Steuersätzen(EÜR)');
INSERT INTO gifi (accno,description) VALUES ('4600', 'Unentgeldliche Wertabgaben');
INSERT INTO gifi (accno,description) VALUES ('4605', 'Entnahme v. Gegenst.o.USt.');
INSERT INTO gifi (accno,description) VALUES ('4610', 'Entnah.d.Untern.f.Zwecke ausserh.d.Untern.7%USt');
INSERT INTO gifi (accno,description) VALUES ('4619', 'Entnahme durch den Untern.f.Zwecke außerhalb d.Untern.(Waren)o.USt');
INSERT INTO gifi (accno,description) VALUES ('4620', 'Entnahme des Untern.f.Zwecke ausserh.d.Untern 16%(Waren)');
INSERT INTO gifi (accno,description) VALUES ('4630', 'Verwendung v.Gegenst.f.Zwecke außerhalb d.Unternehmens 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('4639', 'Verwendung v.Gegenständen f.Zwecke außerhalb d.Untern.o.USt.');
INSERT INTO gifi (accno,description) VALUES ('4640', 'Verw.v.Gegens.f.Zwecke ausserh.d.Untern.16%USt.');
INSERT INTO gifi (accno,description) VALUES ('4645', 'Verwend.v.Gegenst.f.Zwecke außerh.d.Untern.16%USt(Kfz-Nutzung)');
INSERT INTO gifi (accno,description) VALUES ('4646', 'Verwend.f.Gegenst.f.Zwecke außerh.d.Untern.16%USt(Telefonnutzung)');
INSERT INTO gifi (accno,description) VALUES ('4660', 'Unentgeldl.Erbring.sons.Leis.16%USt');
INSERT INTO gifi (accno,description) VALUES ('4670', 'Unentgeltl.Zuw.v Waren 7% Ust');
INSERT INTO gifi (accno,description) VALUES ('4679', 'Unentgeltl.Zuwendung v.Waren o.USt.');
INSERT INTO gifi (accno,description) VALUES ('4680', 'Unentgeltl.Zuw.von Waren 16% Ust');
INSERT INTO gifi (accno,description) VALUES ('4686', 'Unentgeltl.Zuwend.v.Gegens. 16% Ust');
INSERT INTO gifi (accno,description) VALUES ('4689', 'Unentgeldl.Zuw.v.Gegens.ohne Ust');
INSERT INTO gifi (accno,description) VALUES ('4690', 'Nicht steuerbare Umsätze');
INSERT INTO gifi (accno,description) VALUES ('4695', 'Umsatzsteuervergütungen');
INSERT INTO gifi (accno,description) VALUES ('4700', 'Erlösschmälerungen');
INSERT INTO gifi (accno,description) VALUES ('4705', 'Erlösschmälerungen aus steuerfr.Umsätzen §4 Nr.1a UStG');
INSERT INTO gifi (accno,description) VALUES ('4710', 'Erlösschmälerung 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('4720', 'Erlösschmälerung 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('4724', 'Erlösschmäler.a.stfrei.IG Lieferung');
INSERT INTO gifi (accno,description) VALUES ('4725', 'Erlösschmä.Inl.stpfl.EG-Lief. 7%USt');
INSERT INTO gifi (accno,description) VALUES ('4726', 'Erlösschmä.Inl.stpfl.EG-Lief.16%USt');
INSERT INTO gifi (accno,description) VALUES ('4727', 'Erlösschmä.and.EG Land stpfl.Liefer');
INSERT INTO gifi (accno,description) VALUES ('4729', 'Erlösschmälerungen aus im Inland steuerpfl.EG-Lief.15% USt');
INSERT INTO gifi (accno,description) VALUES ('4731', 'Gewährte Skonti 7% USt');
INSERT INTO gifi (accno,description) VALUES ('4735', 'Gewährte Skonti 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('4750', 'Gewährte Boni 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('4760', 'Gewährte Boni 16% USt.');
INSERT INTO gifi (accno,description) VALUES ('4780', 'Gewährte Rabatte 7% USt.');
INSERT INTO gifi (accno,description) VALUES ('4790', 'Gewährte Rabatte 16% Ust.');
INSERT INTO gifi (accno,description) VALUES ('4800', 'Bestandsverä.fertige Erzeugnisse');
INSERT INTO gifi (accno,description) VALUES ('4810', 'Bestandsveränderung-unfertige Erzeu');
INSERT INTO gifi (accno,description) VALUES ('4815', 'Bestandsveränderung-unfertige Leist');
INSERT INTO gifi (accno,description) VALUES ('4820', 'Andere aktivierte Eigenleistungen');
INSERT INTO gifi (accno,description) VALUES ('4830', 'Sonstige Erträge');
INSERT INTO gifi (accno,description) VALUES ('4835', 'Sonstige Erlöse betriebl.u.regelmäß');
INSERT INTO gifi (accno,description) VALUES ('4837', 'Betriebsfremde Erträge nichtaußerorden');
INSERT INTO gifi (accno,description) VALUES ('4840', 'Erträge aus Kursdifferenzen');
INSERT INTO gifi (accno,description) VALUES ('4844', 'Erlöse a.Verk.Sachanlagen steuerfrei§4Nr.1aUStG(b.Buchverlust)');
INSERT INTO gifi (accno,description) VALUES ('4845', 'Erlöse aus Verk.Sachanlagevermögen16% USt (bei Buchverlust)');
INSERT INTO gifi (accno,description) VALUES ('4848', 'Erlöse a.Verk.Sachanlagen steuerfrei§4Nr.1bUStG(b.Buchverlust)');
INSERT INTO gifi (accno,description) VALUES ('4849', 'Erlöse aus Anlagenverkäufen');
INSERT INTO gifi (accno,description) VALUES ('4860', 'Grundstückserträge');
INSERT INTO gifi (accno,description) VALUES ('4900', 'Erträge aus Abgang von AV-Gegenständen');
INSERT INTO gifi (accno,description) VALUES ('4905', 'Ertr.a.d.Abg.v.Gegenst.d.Umlaufverm');
INSERT INTO gifi (accno,description) VALUES ('4910', 'Ertrag a.d.Zuschreib.d.Anlagevermög');
INSERT INTO gifi (accno,description) VALUES ('4915', 'Ertr.a.Zuschreib.d.Umlaufvermögens');
INSERT INTO gifi (accno,description) VALUES ('4920', 'Ertr.a.Herabsetzung d.PWB zu Forderungen');
INSERT INTO gifi (accno,description) VALUES ('4925', 'Ertr. aus abgeschriebenen Forderung');
INSERT INTO gifi (accno,description) VALUES ('4930', 'Ertr.a.d.Auflösung v.Rückstellungen');
INSERT INTO gifi (accno,description) VALUES ('4934', 'Erträge a.d.Auflösung v.SoPo m.Rücklageant.(Exitenzgründungszusch.');
INSERT INTO gifi (accno,description) VALUES ('4939', 'Erträge Aufl. Sopo m.R.(Ansparafa)');
INSERT INTO gifi (accno,description) VALUES ('4941', 'Sachbezüge 7% Ust (Waren)');
INSERT INTO gifi (accno,description) VALUES ('4945', 'Sachbezüge 16% Ust (Waren)');
INSERT INTO gifi (accno,description) VALUES ('4946', 'Verrechnete sons. Sachbezüge keine Waren');
INSERT INTO gifi (accno,description) VALUES ('4960', 'Periodenfremde Erträge nicht außero');
INSERT INTO gifi (accno,description) VALUES ('4970', 'Versicherungsentschädigungen');
INSERT INTO gifi (accno,description) VALUES ('4981', 'Steuerfr.Erträge a.d.Auflös.v.SoPo m.Rücklageanteil');
INSERT INTO gifi (accno,description) VALUES ('4982', 'Sonst.steuerfreie Betriebseinnahmen');
INSERT INTO gifi (accno,description) VALUES ('5190', 'Energiestoffe (Fertigung)');
INSERT INTO gifi (accno,description) VALUES ('5200', 'Wareneingang 0% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5300', 'Wareneingang 7% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5400', 'Wareneingang 16% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5420', 'Innergemein.Erwerb 7% VorSt u. Ust');
INSERT INTO gifi (accno,description) VALUES ('5425', 'Innergem.Erwerb 16% VorSt u. Ust');
INSERT INTO gifi (accno,description) VALUES ('5440', 'Innergem.Erwerb v.Neufahrz.v.Lief.o.USt.Identnr.16%VSt.u.16%USt.');
INSERT INTO gifi (accno,description) VALUES ('5550', 'Steuerfreier innergem.Erwerb');
INSERT INTO gifi (accno,description) VALUES ('5559', 'Steuerfreie Einfuhren');
INSERT INTO gifi (accno,description) VALUES ('5580', 'Wareneinkauf z.allg.Umsatzsteuersatz (EÜR)');
INSERT INTO gifi (accno,description) VALUES ('5581', 'Wareneinkauf z.erm.Umsatzsteuersatz(EÜR)');
INSERT INTO gifi (accno,description) VALUES ('5582', 'Wareneinkauf ohne Vorsteuerabzug(EÜR)');
INSERT INTO gifi (accno,description) VALUES ('5589', 'Gegenkto.3580-3582 b.Aufteilung d.WE n.Steuersätzen(EüR)');
INSERT INTO gifi (accno,description) VALUES ('5600', 'Nicht abziehbare Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5610', 'Nicht abziehb.Vorsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('5650', 'Nicht abziehb.Vorsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('5731', 'Erhaltene Skonti 7% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5735', 'Erhaltene Skonti 16% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5750', 'Erhaltene Boni 7% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5760', 'Erhaltene Boni 16% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5780', 'Erhaltene Rabatte 7% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5790', 'Erhaltene Rabatte 16% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5800', 'Bezugsnebenkosten');
INSERT INTO gifi (accno,description) VALUES ('5820', 'Leergut');
INSERT INTO gifi (accno,description) VALUES ('5840', 'Zölle und Einfuhrabgaben');
INSERT INTO gifi (accno,description) VALUES ('5860', 'Verrechnete Stoffkosten');
INSERT INTO gifi (accno,description) VALUES ('5880', 'Bestandsver.Roh-,Hilfs-.Betriebs.sow.bez.Waren');
INSERT INTO gifi (accno,description) VALUES ('5900', 'Fremdleistungen');
INSERT INTO gifi (accno,description) VALUES ('5901', 'Fremdleistungen 0% Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('5915', 'Leist.v.ausländ.Untern. 7% VSt.u.7%USt.');
INSERT INTO gifi (accno,description) VALUES ('5925', 'Leist.v.ausländ.Untern. 16% VSt.u.16%USt.');
INSERT INTO gifi (accno,description) VALUES ('6010', 'Löhne');
INSERT INTO gifi (accno,description) VALUES ('6020', 'Gehälter');
INSERT INTO gifi (accno,description) VALUES ('6026', 'Tantiemen');
INSERT INTO gifi (accno,description) VALUES ('6027', 'Geschäftsführergehälter');
INSERT INTO gifi (accno,description) VALUES ('6030', 'Aushilfslöhne');
INSERT INTO gifi (accno,description) VALUES ('6040', 'Lohnsteuer für Aushilfe');
INSERT INTO gifi (accno,description) VALUES ('6045', 'Bedienungsgelder');
INSERT INTO gifi (accno,description) VALUES ('6050', 'Ehegattengehalt');
INSERT INTO gifi (accno,description) VALUES ('6060', 'Freiwillige sozi.Aufw.lohnsteuerpflichtig.');
INSERT INTO gifi (accno,description) VALUES ('6069', 'Pauschale Lohnsteuera.sons.Bezüge (z.B.Fahrtkostenzu)');
INSERT INTO gifi (accno,description) VALUES ('6070', 'Krankengeldzuschüsse');
INSERT INTO gifi (accno,description) VALUES ('6080', 'Vermögenswirksame Leistungen');
INSERT INTO gifi (accno,description) VALUES ('6090', 'Fahrtkostenerst.Wohnung/Arbeitsstät');
INSERT INTO gifi (accno,description) VALUES ('6110', 'Gesetzlich soziale Aufwendungen');
INSERT INTO gifi (accno,description) VALUES ('6120', 'Beiträge zur Berufsgenossenschaftr');
INSERT INTO gifi (accno,description) VALUES ('6130', 'Freiwillig soziale Aufwendungen lohnsteuerfrei');
INSERT INTO gifi (accno,description) VALUES ('6147', 'Pauschale Lohnsteuer auf sonst.Bezüge(z.B.Direktversicherung');
INSERT INTO gifi (accno,description) VALUES ('6200', 'Abschreibungen a.immat.Vermögensgeg');
INSERT INTO gifi (accno,description) VALUES ('6205', 'Abschreibung a.d.Geschäft-o.Firmenw');
INSERT INTO gifi (accno,description) VALUES ('6210', 'Außerplan.AfA a.immat.Vermögensgeg.');
INSERT INTO gifi (accno,description) VALUES ('6220', 'Abschreibungen auf Sachanlagen');
INSERT INTO gifi (accno,description) VALUES ('6221', 'Abschreibung auf Gebäude');
INSERT INTO gifi (accno,description) VALUES ('6222', 'Abschreibungen auf Kfz');
INSERT INTO gifi (accno,description) VALUES ('6230', 'Außerplanmäßig Abschr.a.Sachanlagen');
INSERT INTO gifi (accno,description) VALUES ('6231', 'Absetzung f.außergew.techn.u.wirtschaftl.AfA bei Gebäuden');
INSERT INTO gifi (accno,description) VALUES ('6232', 'Absetzung f.außergew.techn.u.wirtschaftl.AfA des Kfz');
INSERT INTO gifi (accno,description) VALUES ('6233', 'Absetzung f.außergew.techn.u.wirtschaftl.AfA sonst.WG');
INSERT INTO gifi (accno,description) VALUES ('6240', 'Abschr.a.Sachanl.aufgr.steuerl.Sondervorschriften');
INSERT INTO gifi (accno,description) VALUES ('6241', 'Sonderabschreibung nach §7g(1)u.(2)EStG (ohne Kfz)');
INSERT INTO gifi (accno,description) VALUES ('6242', 'Sonderabschreibung n.§7g(1)u.(2)EStG (für Kfz)');
INSERT INTO gifi (accno,description) VALUES ('6250', 'Kaufleasing');
INSERT INTO gifi (accno,description) VALUES ('6260', 'Sofortabschreibung GWG');
INSERT INTO gifi (accno,description) VALUES ('6262', 'Abschreibungen auf aktivierte GWG');
INSERT INTO gifi (accno,description) VALUES ('6270', 'Abschreibungen auf Finanzanlagen');
INSERT INTO gifi (accno,description) VALUES ('6275', 'Abschr.a.Wertp.d.Umlaufvermögens');
INSERT INTO gifi (accno,description) VALUES ('6280', 'Forderungsverlust-übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('6281', 'Forderungsverluste 7% USt.(übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('6285', 'Forderungsverluste 16% USt.(übliche Höhe');
INSERT INTO gifi (accno,description) VALUES ('6300', 'Sonstige betriebliche Aufwendungen');
INSERT INTO gifi (accno,description) VALUES ('6303', 'Fremdleistungen');
INSERT INTO gifi (accno,description) VALUES ('6304', 'Sons.Aufw.betriebl. und regelmäßig');
INSERT INTO gifi (accno,description) VALUES ('6305', 'Raumkosten');
INSERT INTO gifi (accno,description) VALUES ('6310', 'Miete');
INSERT INTO gifi (accno,description) VALUES ('6315', 'Pacht');
INSERT INTO gifi (accno,description) VALUES ('6320', 'Heizung');
INSERT INTO gifi (accno,description) VALUES ('6325', 'Gas,Strom, Wasser');
INSERT INTO gifi (accno,description) VALUES ('6330', 'Reinigung');
INSERT INTO gifi (accno,description) VALUES ('6335', 'Instandhaltung betrieb.Räume');
INSERT INTO gifi (accno,description) VALUES ('6338', 'Instandhaltung betrieb.Räume nicht Betriebsverm.');
INSERT INTO gifi (accno,description) VALUES ('6343', 'Abgaben f.betrieb.genutz.Grundbesitz nicht Betriebsverm.');
INSERT INTO gifi (accno,description) VALUES ('6345', 'Sonstige Raumkosten');
INSERT INTO gifi (accno,description) VALUES ('6348', 'Aufwend.f.ein häusliches Arbeitszimmer(abziehb.Anteil)');
INSERT INTO gifi (accno,description) VALUES ('6349', 'Aufwend.f.ein häusliches Arbeitszimmer(nicht abziehb.Anteil)');
INSERT INTO gifi (accno,description) VALUES ('6350', 'Grundstücksaufwendungen');
INSERT INTO gifi (accno,description) VALUES ('6390', 'Zuwend.,Spenden,steuerlich n.abziehbar');
INSERT INTO gifi (accno,description) VALUES ('6358', 'Gründstücksaufwend.f.Gebäude,die nicht z.Betriebsverm.gehören');
INSERT INTO gifi (accno,description) VALUES ('6400', 'Versicherungen');
INSERT INTO gifi (accno,description) VALUES ('6405', 'Versicherungen f.Gebäude,die zum BV gehören');
INSERT INTO gifi (accno,description) VALUES ('6420', 'Beiträge');
INSERT INTO gifi (accno,description) VALUES ('6430', 'Sonstige Abgaben');
INSERT INTO gifi (accno,description) VALUES ('6436', 'Steuerl.abzugs.Verspätungszuschl.u.Zwangsgelder');
INSERT INTO gifi (accno,description) VALUES ('6437', 'Steuerl.n.abzugsf.Verspätungszuschläge u.Zwangsgelder');
INSERT INTO gifi (accno,description) VALUES ('6440', 'Ausgleichsabgabe i.S.d.Schwerbehinterdengesetzes');
INSERT INTO gifi (accno,description) VALUES ('6460', 'Rep.u.Instandhaltungen v.techn.Anlagen u.Maschinen');
INSERT INTO gifi (accno,description) VALUES ('6470', 'Rep.u.Instandhaltungen v.and.Anlagen u.Betriebs-u.Geschäftsausst.');
INSERT INTO gifi (accno,description) VALUES ('6490', 'Sonstige Reparaturen u.Instandhalt.');
INSERT INTO gifi (accno,description) VALUES ('6495', 'Wartungskosten für Hard-u.Software');
INSERT INTO gifi (accno,description) VALUES ('6498', 'Mietleasing');
INSERT INTO gifi (accno,description) VALUES ('6499', 'Gewerbest.zu berücksicht.Mietleasing §8 GewStG');
INSERT INTO gifi (accno,description) VALUES ('6500', 'Fahrzugkosten');
INSERT INTO gifi (accno,description) VALUES ('6520', 'Kfz-Versicherungen');
INSERT INTO gifi (accno,description) VALUES ('6530', 'Laufende Kfz-Betriebskosten');
INSERT INTO gifi (accno,description) VALUES ('6540', 'Kfz-Reparaturen');
INSERT INTO gifi (accno,description) VALUES ('6550', 'Garagenmiete');
INSERT INTO gifi (accno,description) VALUES ('6560', 'Fremdfahrzeuge');
INSERT INTO gifi (accno,description) VALUES ('6595', 'Fremdfahrzeugkosten');
INSERT INTO gifi (accno,description) VALUES ('6570', 'Sonstige Kfz-Kosten');
INSERT INTO gifi (accno,description) VALUES ('6580', 'Mautgebühren');
INSERT INTO gifi (accno,description) VALUES ('6590', 'Fahrzeugkosten f.Kfz,die nicht zum BV gehören');
INSERT INTO gifi (accno,description) VALUES ('6600', 'Werbekosten');
INSERT INTO gifi (accno,description) VALUES ('6610', 'Geschenke abzugsf.');
INSERT INTO gifi (accno,description) VALUES ('6620', 'Geschenke nicht abzugsf.');
INSERT INTO gifi (accno,description) VALUES ('6625', 'Geschenke ausschließl.betrieb.genut');
INSERT INTO gifi (accno,description) VALUES ('6630', 'Repräsentationskosten');
INSERT INTO gifi (accno,description) VALUES ('6640', 'Bewirtungskosten');
INSERT INTO gifi (accno,description) VALUES ('6643', 'Aufmerksamkeiten');
INSERT INTO gifi (accno,description) VALUES ('6644', 'Nicht abzugsfähige Bewirtungskosten');
INSERT INTO gifi (accno,description) VALUES ('6645', 'Nicht abzugsfähige Betriebsausgaben');
INSERT INTO gifi (accno,description) VALUES ('6650', 'Reisekosten Arbeitnehmer');
INSERT INTO gifi (accno,description) VALUES ('6660', 'Reisekosten Arbeitn.Übernachtungsaufwand');
INSERT INTO gifi (accno,description) VALUES ('6663', 'Reisekosten Arbeitn.m.Vorsteuerabzu f.öffentl.Verkehrsm.');
INSERT INTO gifi (accno,description) VALUES ('6664', 'Reisekosten Arbeitn.Verpflegungmehr');
INSERT INTO gifi (accno,description) VALUES ('6668', 'Kilometerentgelderstattung Arbeitnehmer');
INSERT INTO gifi (accno,description) VALUES ('6670', 'Reisekosten Unternehmer');
INSERT INTO gifi (accno,description) VALUES ('6673', 'Reisek.Untern.m.Vorsteuerabzug (f.öffentl.Verkehrsm.');
INSERT INTO gifi (accno,description) VALUES ('6674', 'Reisekosten Untern.Verpflegungsmehr');
INSERT INTO gifi (accno,description) VALUES ('6680', 'Reisekosten Untern.Übernachtungsauf');
INSERT INTO gifi (accno,description) VALUES ('6688', 'Fahrten zw.Wohn.und Arbeitsstätte (nicht abziehb.Teil)');
INSERT INTO gifi (accno,description) VALUES ('6689', 'Fahrten zw.Wohn.-und Arbeitsstätte (Haben)');
INSERT INTO gifi (accno,description) VALUES ('6700', 'Kosten der Warenabgabe');
INSERT INTO gifi (accno,description) VALUES ('6710', 'Verpackungsmaterial');
INSERT INTO gifi (accno,description) VALUES ('6740', 'Ausgangsfracht');
INSERT INTO gifi (accno,description) VALUES ('6760', 'Transportversicherung');
INSERT INTO gifi (accno,description) VALUES ('6770', 'Verkaufsprovision');
INSERT INTO gifi (accno,description) VALUES ('6780', 'Fremdarbeiten');
INSERT INTO gifi (accno,description) VALUES ('6790', 'Aufwand für Gewährleistungen');
INSERT INTO gifi (accno,description) VALUES ('6800', 'Porto');
INSERT INTO gifi (accno,description) VALUES ('6805', 'Telefon');
INSERT INTO gifi (accno,description) VALUES ('6810', 'Telefax');
INSERT INTO gifi (accno,description) VALUES ('6815', 'Bürobedarf');
INSERT INTO gifi (accno,description) VALUES ('6820', 'Zeitschriften, Bücher');
INSERT INTO gifi (accno,description) VALUES ('6821', 'Fortbildungskosten');
INSERT INTO gifi (accno,description) VALUES ('6822', 'Freiwillige Sozialleistungen');
INSERT INTO gifi (accno,description) VALUES ('6825', 'Rechts- und Beratungskosten');
INSERT INTO gifi (accno,description) VALUES ('6827', 'Abschluß- und Prüfungskosten');
INSERT INTO gifi (accno,description) VALUES ('6830', 'Buchführungskosten');
INSERT INTO gifi (accno,description) VALUES ('6835', 'Mieten für Einrichtungen');
INSERT INTO gifi (accno,description) VALUES ('6840', 'Mieten für Einrichtungen');
INSERT INTO gifi (accno,description) VALUES ('6845', 'Werkzeuge und Kleingeräte');
INSERT INTO gifi (accno,description) VALUES ('6850', 'Betriebsbedarf');
INSERT INTO gifi (accno,description) VALUES ('6855', 'Nebenkosten des Geldverkehrs');
INSERT INTO gifi (accno,description) VALUES ('6859', 'Aufwend.f.Abraum-u.Abfallbeseitigung');
INSERT INTO gifi (accno,description) VALUES ('6860', 'Nicht abziehbare Vorsteuer');
INSERT INTO gifi (accno,description) VALUES ('6865', 'Nicht abziehbare Vorsteuer 7%');
INSERT INTO gifi (accno,description) VALUES ('6870', 'Nicht abziehbare Vorsteuer 16%');
INSERT INTO gifi (accno,description) VALUES ('6880', 'Aufwendungen aus Kursdifferenzen');
INSERT INTO gifi (accno,description) VALUES ('6895', 'Abgänge Sachanlagen Restbuchwert');
INSERT INTO gifi (accno,description) VALUES ('6900', 'Verluste aus Anlagenabgang');
INSERT INTO gifi (accno,description) VALUES ('6926', 'Einstellungen in SoPo m.Rücklageanteil (Ansparabschreibung');
INSERT INTO gifi (accno,description) VALUES ('6928', 'Einstellungen in SoPo m.Rücklageanteil (Existenzgründungsrücklage');
INSERT INTO gifi (accno,description) VALUES ('6960', 'Periodenfremde Aufwend.(soweit n.außerordentlich');
INSERT INTO gifi (accno,description) VALUES ('6967', 'Betriebsfremde Aufwendungen soweit n.außerord.');
INSERT INTO gifi (accno,description) VALUES ('6970', 'Kalkulatorischer Unternehmerlohn');
INSERT INTO gifi (accno,description) VALUES ('6974', 'Kalkulatorische Zinsen');
INSERT INTO gifi (accno,description) VALUES ('6976', 'Kalkulatorische Aschreibungen');
INSERT INTO gifi (accno,description) VALUES ('6978', 'Kalkulatorische Wagnisse');
INSERT INTO gifi (accno,description) VALUES ('6979', 'Kalkulatorischer Lohn f.unentgeltl.Mitarbeiter');
INSERT INTO gifi (accno,description) VALUES ('7000', 'Erträge aus Beteiligungen');
INSERT INTO gifi (accno,description) VALUES ('7100', 'Sonstige Zinsen und ähnliche Erträge');
INSERT INTO gifi (accno,description) VALUES ('7120', 'Zinsähnliche Erträge');
INSERT INTO gifi (accno,description) VALUES ('7130', 'Diskonterträge');
INSERT INTO gifi (accno,description) VALUES ('7300', 'Zinsen und ähnl.Aufwendungen');
INSERT INTO gifi (accno,description) VALUES ('7305', 'Zinsaufwendung-betriebliche Steuern §223aAO');
INSERT INTO gifi (accno,description) VALUES ('7310', 'Zinsaufwendung f.kurzf.Verbindlichk');
INSERT INTO gifi (accno,description) VALUES ('7320', 'Zinsaufwendung f.langf.Verbindlichk');
INSERT INTO gifi (accno,description) VALUES ('7325', 'Zinsaufwend.f.Gebäude,die z.Betriebsvermögen gehören');
INSERT INTO gifi (accno,description) VALUES ('7326', 'Zinsen zur Finanzierung Anlagevermögen');
INSERT INTO gifi (accno,description) VALUES ('7330', 'Zinsähnliche Aufwendungen');
INSERT INTO gifi (accno,description) VALUES ('7340', 'Diskontaufwendung');
INSERT INTO gifi (accno,description) VALUES ('7400', 'Außerordentliche Erträge');
INSERT INTO gifi (accno,description) VALUES ('7401', 'Außerordentliche Erträge finanzwirksam');
INSERT INTO gifi (accno,description) VALUES ('7450', 'Außerordentliche Erträge nicht finanzwirksam');
INSERT INTO gifi (accno,description) VALUES ('7500', 'Außerordentliche Aufwendung');
INSERT INTO gifi (accno,description) VALUES ('7600', 'Körperschaftssteuer');
INSERT INTO gifi (accno,description) VALUES ('7608', 'Solidaritätszuschlag');
INSERT INTO gifi (accno,description) VALUES ('7609', 'Solidaritätszuschlag für Vorjahr');
INSERT INTO gifi (accno,description) VALUES ('7610', 'Gewerbesteuer');
INSERT INTO gifi (accno,description) VALUES ('7632', 'Kapitalertragssteuer 20%');
INSERT INTO gifi (accno,description) VALUES ('7634', 'Anrechenb.Soli auf Kapitalertragssteuer 20%');
INSERT INTO gifi (accno,description) VALUES ('7635', 'Zinsabschlagsteuer');
INSERT INTO gifi (accno,description) VALUES ('7638', 'Anrechb.Solidari.zuschlag a.Zinsabschlagst.');
INSERT INTO gifi (accno,description) VALUES ('7640', 'Stnachzahl.Vorj.v.Einkomm u.Ertrag');
INSERT INTO gifi (accno,description) VALUES ('7642', 'Sterstat.Vorj.Steuer v.Eink.u.Ertrag');
INSERT INTO gifi (accno,description) VALUES ('7644', 'Ertr.a.d.Aufl.v.Rücks.f.St.v.Ein.Er');
INSERT INTO gifi (accno,description) VALUES ('7650', 'Sonstige Betriebssteuern');
INSERT INTO gifi (accno,description) VALUES ('7675', 'Verbrauchssteuer');
INSERT INTO gifi (accno,description) VALUES ('7678', 'Ökosteuer');
INSERT INTO gifi (accno,description) VALUES ('7680', 'Grundsteuer');
INSERT INTO gifi (accno,description) VALUES ('7684', 'Grundsteuer f.Gebäude,die nicht z.Betriebsvermögen geh');
INSERT INTO gifi (accno,description) VALUES ('7685', 'Kfz-Steuer');
INSERT INTO gifi (accno,description) VALUES ('7690', 'Steuernachzahlung Vorj.f.sons.Steue');
INSERT INTO gifi (accno,description) VALUES ('7692', 'Steuererstattung Vorj.f.sons.Steuer');
INSERT INTO gifi (accno,description) VALUES ('7694', 'Erträge a.d.Aufl.v. Rück.f.sons.Ste');
INSERT INTO gifi (accno,description) VALUES ('7745', 'Entnahmen a.satzungsmäßigen Rücklagen');
INSERT INTO gifi (accno,description) VALUES ('9000', 'Saldenverträge,Sachkonten');
INSERT INTO gifi (accno,description) VALUES ('9008', 'Saldenverträge,Debitoren');
INSERT INTO gifi (accno,description) VALUES ('9009', 'Saldenverträge,Kreditoren');
INSERT INTO gifi (accno,description) VALUES ('9090', 'Summenvortragskonto');
