-- @tag: release_3_0_0
-- @description: Abhängigkeitsscript für Release 3.0.0
-- @depends: remove_menustyle_v4 remove_menustyle_xml add_batch_printing_to_full_access auth_schema_normalization_1 session_content_auto_restore add_api_token password_hashing
