-- @tag: release_3_9_1
-- @description: Abhängigkeitsscript für Release 3.9.1
-- @depends: release_3_9_0 right_sales_order_item_search rights_view_cp_report rights_order_reports_amounts right_custom_data_report right_part_master_data_prices right_financial_controlling right_sales_report
